require u-boot-common.inc
require u-boot.inc

DEPENDS += "bc-native dtc-native"

SRC_URI += "\
            file://0001-mvebu-Change-the-default-system-prompt-for-Marvell-b.patch \
            file://0002-arm64-a37xx-defconfigs-enable-CONFIG_MVNETA.patch \
            file://0003-net-e1000-Temporarely-bypass-PHY-HW-reset-temout.patch \
            file://0004-kconfig-mvebu-remove-unused-config.patch \
            file://0005-arm64-mvebu-config-Move-duplicate-configurations-to-.patch \
            file://0006-arm64-mvebu-config-move-env-to-the-end-of-the-4MB-bo.patch \
            file://0007-arm64-mvebu-config-Enable-CONFIG_ENV_OVERWRITE.patch \
            file://0008-arm64-mvebu-config-Set-CONFIG_BOOTCOMMAND.patch \
            file://0009-arm64-mvebu-a8k-config-Add-missing-config-options.patch \
            file://0010-arm64-dts-armada-8040-mcbin-set-cp1-comphy-to-SGMII2.patch \
            file://0011-phy-marvell-add-comphy-type-PHY_TYPE_USB3.patch \
            file://0012-phy-marvell-rename-comphy-related-definitions-to-COM.patch \
            file://0013-phy-marvell-add-missing-speed-during-info-prints.patch \
            file://0014-phy-marvell-cp110-initialize-only-enabled-UTMI-units.patch \
            file://0015-phy-marvell-cp110-utmi-update-analog-parameters-acco.patch \
            file://0016-phy-marvell-fix-several-minor-bugs-in-comphy_probe.patch \
            file://0017-phy-marvell-save-comphy_map_data-priv-structure.patch \
            file://0018-phy-marvell-add-RX-training-command.patch \
            file://0019-phy-marvell-cp110-add-basic-AP-auto-negotiation-supp.patch \
            file://0020-phy-marvell-enable-comphy-info-prints-for-all-device.patch \
            file://0021-phy-marvell-cp110-remove-unused-definitions.patch \
            file://0022-phy-marvell-cp110-let-the-firmware-configure-the-com.patch \
            file://0023-phy-marvell-cp110-let-the-firmware-configure-comphy-.patch \
            file://0024-phy-marvell-cp110-let-the-firmware-configure-comphy-.patch \
            file://0025-phy-marvell-cp110-let-the-firmware-configure-comphy-.patch \
            file://0026-phy-marvell-cp110-let-the-firmware-perform-training-.patch \
            file://0027-phy-marvell-cp110-let-the-firmware-configure-comphy-.patch \
            file://0028-phy-marvell-cp110-remove-both-phy-and-pipe-selector-.patch \
            file://0029-phy-marvell-cp110-clean-up-driver-after-it-was-moved.patch \
            file://0030-doc-dt-bindings-add-Marvell-comphy-binding.patch \
            file://0031-phy-marvell-cp110-update-mode-parameter-for-pcie-pow.patch \
            file://0032-phy-marvell-pass-sgmii-id-to-firmware.patch \
            file://0033-phy-marvell-fix-handling-of-unconnected-comphy.patch \
            file://0034-phy-marvell-cp110-mark-u-boot-power-off-calls.patch \
            file://0035-phy-marvell-allow-to-initialize-up-to-6-USB-ports.patch \
            file://0036-phy-marvell-a3700-let-the-firmware-configure-the-phy.patch \
            file://0037-arm64-dts-a70x0-align-a7040-db-to-board-setup-A.patch \
            file://0038-arm64-dts-a80x0-Enable-10GB-CP0-10G-CP1-and-RGMII0-C.patch \
            file://0039-spi-set-spi-speed-to-the-minimum-between-controller-.patch \
            file://0040-arm64-dts-a70x0-a80x0-Correct-spi-flash-compatible-s.patch \
            file://0041-arm64-dts-a70x0-a80x0-update-board-model-s-name-to-a.patch \
            file://0042-arm64-dts-a70x0-a80x0-create-a-shared-dtsi-file-for-.patch \
            file://0043-doc-net-add-sfi-to-supported-phy-modes.patch \
            file://0044-arm64-dts-a70x0-a80x0-add-io-expander-gpio-node-in-i.patch \
            file://0045-usb-mvebu-lower-vbus-in-usb-stop-command.patch \
            file://0046-ehci-mvebu-toggle-vbus-for-EHCI-start-and-stop.patch \
            file://0047-arm64-dts-a70x0-a80x0-Add-VBUS-regulator-supply-to-U.patch \
            file://0048-arm64-dts-mcbin-Adjust-the-mcbin-USB-regulator-param.patch \
            file://0049-usb-a8k-remove-board-specific-code-for-vbus-regulato.patch \
            file://0050-arm64-dts-mvebu-remove-unused-nodes-from-marvell-dev.patch \
            file://0051-arm64-dts-cp110-unite-cp110-master-slave-dtsi-files-.patch \
            file://0052-dts-mvebu-a375-Enable-mdio-node.patch \
            file://0053-dts-mvebu-a7-8k-a8kp-Align-mdio-xmdio-nodes-to-marve.patch \
            file://0054-arm64-mvebu-armada-8040-mcbin-enable-networking-in-d.patch \
            file://0055-net-mvpp2-fix-traffic-stuck-after-PHY-start-error.patch \
            file://0056-net-mvpp2-fix-checkpatch-warnings.patch \
            file://0057-phy-introduce-AP-interface-mode.patch \
            file://0058-net-mvpp2-Allow-to-support-802.3ap-Backplane-Auto-Ne.patch \
            file://0059-net-mvpp2-mark-phy-as-invalid-in-case-of-missing-app.patch \
            file://0060-net-mvpp2-allow-MDIO-registration-for-fixed-links.patch \
            file://0061-net-mvpp2-add-CP115-port1-10G-5G-SFI-support.patch \
            file://0062-net-mvpp2-terminate-RX-pause-frames-in-GoP.patch \
            file://0063-phy-introduce-1000BaseX-and-2500BaseX-modes.patch \
            file://0064-net-mvpp2-add-1000BaseX-and-2500BaseX-ppv2-support.patch \
            file://0065-phy-net-Increase-autoneg-timeout-from-4-to-8-seconds.patch \
            file://0066-doc-net-add-AP-to-supported-phy-modes.patch \
            file://0067-net-phy-fix-88E1510-PHY-initialization.patch \
            file://0068-net-phy-add-support-for-88E2110-phy.patch \
            file://0069-arm64-mvebu-a8k-config-move-CONFIG_E1000-to-defconfi.patch \
            file://0070-arm64-dts-cp110-declare-missing-I2C-controller.patch \
            file://0071-arm64-dts-apn806-add-ap_-prefix-for-spi0-node-and-ic.patch \
            file://0072-arm64-dts-a80x0-add-a8040-db-device-tree-with-setup-.patch \
            file://0073-arm64-dts-a80x0-add-a8040-db-device-tree-with-setup-.patch \
            file://0074-arm64-dts-a80x0-add-a8040-db-device-tree-with-setup-.patch \
            file://0075-arm64-dts-a80x0-add-a8040-db-device-tree-with-setup-.patch \
            file://0076-arm64-dts-a80x0-add-a8040-db-device-tree-with-setup-.patch \
            file://0077-arm64-mvebu-config-a8k-add-support-for-Armada-8k-OCP.patch \
            file://0078-arm64-dts-a80x0-add-support-for-Armada-8k-OCP-board.patch \
            file://0079-arm64-dts-a7020-add-support-for-A7020-AMC-board.patch \
            file://0080-arm64-dts-a70x0-add-support-for-7040-pcac-board.patch \
            file://0081-arm64-dts-a70x0-add-a7040-db-device-tree-for-setup-B.patch \
            file://0082-arm64-dts-a70x0-add-a7040-db-device-tree-for-setup-C.patch \
            file://0083-arm64-dts-a70x0-add-a7040-db-device-tree-for-setup-D.patch \
            file://0084-arm64-dts-a70x0-add-a7040-db-device-tree-for-setup-E.patch \
            file://0085-arm64-mvebu-config-enable-MDIO.patch \
            file://0086-phy-mvebu-add-command-to-download-firmware-for-Marve.patch \
            file://0087-config-a8k-enable-support-for-x3310-phy-firmware-dow.patch \
            file://0088-dts-a3700-add-io-expander-gpio-node-in-i2c-node.patch \
            file://0089-arm64-mvebu-config-a37xx-enable-pca953x.patch \
            file://0090-mmc-xenon_sdhci-set-signal-voltage-and-max-base-cloc.patch \
            file://0091-arm64-config-a37xx-enable-regulator-gpio-support.patch \
            file://0092-arm64-dts-armada-3720-db-declare-regulator-supplies.patch \
            file://0093-mmc-xenon-document-xenon-sdhci-device-tree-binding.patch \
            file://0094-arm64-dts-armada-3720-db-add-phy2-node-for-SATA-inte.patch \
            file://0095-arm64-dts-armada-3720-db-update-USB-comphy-type.patch \
            file://0096-arm64-dts-armada-3720-db-update-model-and-compatible.patch \
            file://0097-arm64-a37xx-enable-serdes-lane-2-mux-for-SATA-PHY.patch \
            file://0098-arm64-dts-a3700-set-lane2-comphy-speed-to-6Gbps.patch \
            file://0099-arm64-dts-a37xx-update-comphy-lane-numbers.patch \
            file://0100-arm64-dts-armada-3720-db-add-dts-for-more-devel-boar.patch \
            file://0101-power-regulator-add-support-for-regulator-force-boot.patch \
            file://0102-arm64-mvebu-a8k-Turn-off-regulators-on-early-board-i.patch \
            file://0103-cmd-mem-add-ir-command-support.patch \
            file://0104-arm64-mvebu-a8k-add-soc-type-and-revision-printing-i.patch \
            file://0105-arm64-mvebu-cmd-introduce-AVS-command.patch \
            file://0106-arm64-mvebu-cmd-add-memory-map-command-for-a8k.patch \
            file://0107-thermal-introduce-mvebu-thermal-driver.patch \
            file://0108-arm64-mvebu-cmd-add-thermal-sensor-command.patch \
            file://0109-arm64-mvebu-a8k-config-enable-tsen-command.patch \
            file://0110-arm64-dts-a8k-add-thermal-device-tree-nodes.patch \
            file://0111-i2c-mv_i2c-mvtwsi-correct-i2c-address-send-order.patch \
            file://0112-arm64-mvebu-cmd-add-hardware-information-command.patch \
            file://0113-arm64-mvebu-cmd-add-support-to-load-HW-info-during-e.patch \
            file://0114-arm64-mvebu-a37xx-a8k-config-enable-hw_info-command-.patch \
            file://0115-cmd-mvebu-initial-support-for-SAR-infrastructure.patch \
            file://0116-arm64-dts-a8k-add-sar-device-tree-node.patch \
            file://0117-arm64-mvebu-config-a8k-enable-sar-command-by-default.patch \
            file://0118-efuse-mvebu-add-DM-and-dts-support-for-efuse-driver.patch \
            file://0119-efuse-mvebu-use-High-density-efuse-operation.patch \
            file://0120-efuse-mvebu-add-Low-Density-LD-efuse-operation-code.patch \
            file://0121-arm64-mvebu-dts-a8k-add-efuse-nodes.patch \
            file://0122-arm64-dts-a8k-sync-compatible-string-with-Linux-v5.0.patch \
            file://0123-checkpatch-ignore-change-id-errors.patch \
            file://0124-arm64-mvebu-a8k-set-cpuidle.off-1-in-bootargs-for-A8.patch \
            file://0125-arm64-mvebu-configs-use-distro-compatible-fdt_addr_r.patch \
            file://0126-arm64-mvebu-configs-use-distro-compatible-ramdisk_ad.patch \
            file://0127-arm64-mvebu-configs-use-distro-compatible-kernel_add.patch \
            file://0128-mvebu-config-use-different-env-addresses.patch \
            file://0129-sar-mvebu-add-chip-sample-at-reset-driver.patch \
            file://0130-arm64-mvebu-clock-a8k-introduce-basic-clock-driver.patch \
            file://0131-arm64-mvebu-soc-a8k-add-soc-early-init.patch \
            file://0132-arm64-mvebu-a8k-add-clock-info-prints.patch \
            file://0133-arm64-mvebu-config-a8k-mcbin-enable-SAR.patch \
            file://0134-arm64-mvebu-a8k-add-llc-info-print.patch \
            file://0135-arm64-mvebu-soc-a8k-correct-the-print-of-AP80x-new-r.patch \
            file://0136-arm64-mvebu-soc-a8k-add-DEVICE_ID-for-new-platforms.patch \
            file://0137-arm64-mvebu-soc-a8k-add-API-for-returning-SoC-sub-re.patch \
            file://0138-net-mvneta-handle-bad-RX-descriptor.patch \
            file://0139-phy-marvell-add-support-for-SFI1.patch \
            file://0140-arm64-dts-armada-add-new-SoC-level-DT-for-ap80x.patch \
            file://0141-arm64-dts-a3900-add-Armada3900-device-tree-with-setu.patch \
            file://0142-arm64-dts-a3900-add-Armada3900-device-tree-with-setu.patch \
            file://0143-sar-mvebu-add-sampled-at-reset-driver-for-AP807.patch \
            file://0144-mtd-rawnand-pxa3xx-add-SoC-specific-enable-function.patch \
            file://0145-arm64-mvebu-config-a8k-enable-NAND-support.patch \
            file://0146-arm64-dts-a8k-remove-phy-speed-property-for-some-com.patch \
            file://0147-arm64-mvebu-a8k-align-memory-regions.patch \
            file://0148-arm64-mvebu-dts-a8k-align-comphy-and-network-configu.patch \
            file://0149-arm64-mvebu-dts-a8k-align-network-and-comphy-configu.patch \
            file://0150-arm64-dts-armada-8040-mcbin-fix-typo-in-the-model-na.patch \
            file://0151-arm64-mvebu-do-not-map-firmware-RT-service-region.patch \
            file://0152-arm64-allow-to-use-platform-specific-sync-abort.patch \
            file://0153-arm64-mvebu-add-platform-specific-synchronous-except.patch \
            file://0154-arch-arm-dts-Enable-efuses-on-Armada-3900-boards.patch \
            file://0155-arm64-dts-a3900-update-configuration-document.patch \
            file://0156-arm64-mvebu-config-enable-ethaddr-editing.patch \
            file://0157-arm64-dts-a8k-align-regulator-naming.patch \
            file://0158-usb-xhci-mvebu-add-current-limiter-support.patch \
            file://0159-arm64-dts-a8k-add-regulator-current-limiter-to-USB3.patch \
            file://0160-arm64-dts-remove-unused-armada-7040-db-nand-device-t.patch \
            file://0161-arm64-dts-a8k-add-phy-speed-property-for-all-sfi-com.patch \
            file://0162-arm64-dts-a7k-add-missing-phy-speed-property-for-sgm.patch \
            file://0163-pinctrl-mvebu-apply-SDHCI-PHY-config-for-A7K.patch \
            file://0164-mmc-xenon-sdhci-correct-the-host-speed-configuration.patch \
            file://0165-arm64-mvebu-dts-a8k-add-missing-SDHCI-regulators.patch \
            file://0166-arm64-mvebu-config-a8k-mcbin-enable-CONFIG_DISPLAY_B.patch \
            file://0167-arm64-mvebu-config-update-default-bootcmd.patch \
            file://0168-spi-kirkwood-support-extended-baud-rates.patch \
            file://0169-arm64-dts-a8k-update-SPI-max-frequency.patch \
            file://0170-spi-dt-binding-introduce-mvebu-spi-binding.patch \
            file://0171-spi-kirkwood-add-direct-write-mode.patch \
            file://0172-arm64-dts-a8k-add-spi-direct-access-mapping.patch \
            file://0173-scripts-config-add-script-to-manipulate-.config.patch \
            file://0174-arm64-mvebu-clock-a3700-introduce-clock-driver.patch \
            file://0175-arm64-mvebu-a3700-override-print_cpuinfo.patch \
            file://0176-arm64-config-a3700-enable-board-information-display.patch \
            file://0177-mmc-add-a-Kconfig-option-to-enable-the-support-for-M.patch \
            file://0178-arm64-mvebu-config-add-SD-eMMC-definitions-to-Armada.patch \
            file://0179-scripts-update-checkpatch-configuration.patch \
            file://0180-arm64-mvebu-config-add-pci-pcie_bus_safe-to-default-.patch \
            file://0181-mmc-xenon_sdhci-add-support-for-HS200-mode.patch \
            file://0182-arm64-mvebu-config-a3700-add-support-for-HS200-mode.patch \
            file://0183-arm64-mvebu-config-increase-the-malloc-size-to-16MB.patch \
            file://0184-ata-ahci-support-disk-insertion-after-boot.patch \
            file://0185-arm-mvebu-db-88f6820-add-SPI-parameters-for-environm.patch \
            file://0186-cmd-mvebu-bubt-add-support-for-legacy-Marvell-SoCs.patch \
            file://0187-arm-mvebu-config-db-88f6820-gp-add-bubt-command-to-t.patch \
            file://0188-spi-kirkwood-use-clock-API-for-reading-the-core-cloc.patch \
            file://0189-arm64-mvebu-config-set-the-maximum-slave-SPI-speed-t.patch \
            file://0190-mtd-spi-add-support-for-Macronix-mx25u3235f-device.patch \
            file://0191-doc-mvebu-introduce-Marvell-documentation.patch \
            file://0192-pci-aardvark-move-setting-of-reference-clock-to-the-.patch \
            file://0193-arm64-mvebu-a8k-move-firmware-related-definitions-to.patch \
            file://0194-arm64-mvebu-a3700-use-smc-call-for-obtaining-memory-.patch \
            file://0195-arm64-mvebu-config-a3700-do-not-use-default-device-t.patch \
            file://0196-arm64-mvebu-dts-armada-8040-db-G-Add-dual-PCIe-x4-co.patch \
            file://0197-arm64-mvebu-dts-armada-8040-db-H-Add-dual-PCIe-x4-wi.patch \
            file://0198-arm64-mvebu-a3900-fix-the-USB-2.0-TX-amplitude.patch \
            file://0199-nand-pxa3xx-allow-pxa3xx_nand_info-to-be-used-outsid.patch \
            file://0200-cmd-mvebu-nand_oem-add-command-to-prepare-restore-oe.patch \
            file://0201-cmd-mvebu-add-nand-oem-command-to-the-build-system.patch \
            file://0202-net-switch-mv88e6xxx-add-support-for-peridot-and-top.patch \
            file://0203-net-switch-mv88e6xxx-add-legacy-switch-support.patch \
            file://0204-net-switch-mv88e6xxx-add-cpu-port-support.patch \
            file://0205-net-switch-mv88e6xxx-add-port-setup-in-initializatio.patch \
            file://0206-net-switch-mv88e6xxx-add-phy-copper-control-setting-.patch \
            file://0207-arm64-mvebu-a8k-Simplify-the-SoC-information-index-l.patch \
            file://0208-net-switch-mv88e6xxx-add-88E6390X-support.patch \
            file://0209-arm64-mvebu-dts-armada8040-add-Cybertan-board-suppor.patch \
            file://0210-arm64-mvebu-init-all-enabled-pinctrl-nodes.patch \
            file://0211-dts-a3900-enable-MDIO-and-network-interfaces.patch \
            file://0212-arm64-mvebu-config-espressobin-enable-mv88e6xxx-swit.patch \
            file://0213-arm64-mvebu-dts-espressobin-add-topaz-switch-support.patch \
            file://0214-arm64-mvbeu-dts-espressobin-enable-sd-card-support.patch \
            file://0215-arm64-mvebu-config-espressobin-include-support-for-G.patch \
            file://0216-dts-mvebu-espressobin-Add-optional-eMMC-device.patch \
            file://0217-arm64-mvebu-espressobin-add-support-for-the-variant-.patch \
            file://0218-arm64-mvebu-config-remove-tftpput-cmd-from-all-Marve.patch \
            file://0219-arm64-mvebu-a37xx-fix-the-boot-from-eMMC-handling.patch \
            file://0220-i2c-mv_i2c-implement-handler-required-by-i2c-reset-c.patch \
            file://0221-i2c-mv_i2c-warn-if-not-supported-speed-mode-chosen.patch \
            file://0222-arm64-mvebu-espressobin-fix-eMMC-configuration-offse.patch \
            file://0223-arm64-mvebu-dts-espressobin-replace-the-lincese-head.patch \
            file://0224-arm64-mvebu-config-espressobin-add-support-for-ISSI-.patch \
            file://0225-arm64-mvebu-dts-mcbin-add-support-Single-Shot-varian.patch \
            file://0226-arm64-mvebu-dts-a37xx-add-DDR4-db-C-rev-3.x-dts.patch \
            file://0227-arm64-mvebu-extend-the-nfsroot-value-for-better-comp.patch \
            file://0228-cmd-mvebu-add-mv_fw_info-command-to-get-service-CPU-.patch \
            file://0229-cmd-mvebu-add-mv_get_counters-command-to-get-MIB-cou.patch \
            file://0230-spi-mvebu_a3700_spi-support-fifo-mode.patch \
            file://0231-spi-mvebu_a3700_spi-replace-1-byte-shift-operation-b.patch \
            file://0232-arm64-mvebu-config-a3700-enable-fixed-regulator.patch \
            file://0233-arm64-mvebu-dts-a37xx-add-SD-slot-power-supply-regul.patch \
            file://0234-arm64-mvebu-soc-introduce-prints-for-cn913x-boards.patch \
            file://0235-cmd-mvebu-sar-enable-sample-at-reset-driver-for-AP80.patch \
            file://0236-arm64-mvebu-dts-ap80x-extend-emmc-pin-description.patch \
            file://0237-arm64-mvebu-extend-the-mmio-region.patch \
            file://0238-arm64-mvebu-sar-ap807-update-clocking-information.patch \
            file://0239-arm64-mvebu-dts-a37xx-description-with-B-C-board-typ.patch \
            file://0240-arm64-mvebu-common-add-cpuidle-default-initializatio.patch \
            file://0241-arm64-mvebu-dts-a8k-add-rtc-device-tree-node.patch \
            file://0242-rtc-marvell-rtc-introduce-RTC-driver.patch \
            file://0243-defconfig-enable-rtc-driver-and-date-command.patch \
            file://0244-phy-marvell-fix-pll-initialization-for-second-utmi-p.patch \
            file://0245-phy-marvell-add-extra-comment-clarifying-utmi-regist.patch \
            file://0246-phy-marvell-utmi-update-utmi-config-which-fixes-usb2.patch \
            file://0247-phy-mvebu-add-more-debug-prints.patch \
            file://0248-phy-mvebu-use-better-variable-naming.patch \
            file://0249-arm64-mvebu-add-prints-about-u-boot-and-environment-.patch \
            file://0250-arm64-mvebu-common-add-eth4-address-to-def-env.patch \
            file://0251-arm64-mvebu-common-increase-wait-time-for-usb-hub-po.patch \
            file://0252-usb-hub-increase-usb-port-reset-time-as-a-W-A-for-so.patch \
            file://0253-pinctrl-armada-37xx-remove-SPI-CS-control-from-UART2.patch \
            file://0254-efuse-mvebu-efuse-flag-support.patch \
            file://0255-arm64-mvbeu-config-a8k-enable-EFUSE-support.patch \
            file://0256-cmd-mvebu-fix-partition-handling-in-bubt-command.patch \
            file://0257-arm64-mvebu-common-add-configurable-boot-device-and-.patch \
            file://0258-arm64-mvebu-dts-fix-efuse-entries-and-OTP-base-addre.patch \
            file://0259-arm-mvebu-config-db-88f6820-gp-enable-DISTRO_DEFAULT.patch \
            file://0260-arm-mvebu-config-db-88f6820-gp-enable-support-for-In.patch \
            file://0261-pci-mvebu-fixup-classid-for-for-first-device-on-firs.patch \
            file://0262-arm-mvebu-common-provide-defaults-enviroments.patch \
            file://0263-arm-mvebu-trigger-the-pcie-enumeration-during-early-.patch \
            file://0264-arm64-mvebu-dts-remove-references-to-PCIe-IO-space.patch \
            file://0265-scripts-update-checkpatch-to-the-current-kernel-vers.patch \
            file://0266-arm-mvebu-a38x-support-external-dram-code.patch \
            file://0267-arm-dts-marvell-add-Armada-7020-ComExpress-board-des.patch \
            file://0268-efuse-a3700-add-efuse-and-mailbox-driver.patch \
            file://0269-cmd-mvebu-add-efuse-command-support.patch \
            file://0270-arm64-mvebu-config-enable-efuse-support-on-a3700-pla.patch \
            file://0271-arm64-mvebu-config-create-dedicated-config-for-A7020.patch \
            file://0272-pinctrl-mvebu-allow-proper-SD-MMC-PHY-MUX-setting-in.patch \
            file://0273-arm64-mvebu-dts-a8k-switch-to-8-bit-ECC-NAND-setting.patch \
            file://0274-arm64-mvebu-dts-a8k-fix-the-pcie-memory-size.patch \
            file://0275-arm64-mvebu-dts-cn913x-import-device-trees.patch \
            file://0276-arm64-mvebu-cn913x-introduce-new-SoC-family.patch \
            file://0277-arm64-mvebu-config-cn91xx-add-configuration-for-the-.patch \
            file://0278-scripts-ci-import-scripts-from-SDK10.1.patch \
            file://0279-pcie-designware-mvebu-do-not-configure-ATU-for-IO-wh.patch \
            file://0280-arm64-dts-armada-8040-mcbin-fix-PCIE-GPIO-type.patch \
            file://0281-arm64-dts-cn9131-db-fix-CP1-PCIE-GPIO-type.patch \
            file://0282-armv8-cavium-Add-ThunderX-register-definitions.patch \
            file://0283-armv8-cavium-Add-ThunderX-TWSI-driver.patch \
            file://0284-usb-Add-Cavium-ThunderX-xHCI-support.patch \
            file://0285-armv8-cavium-Add-cpucore-command.patch \
            file://0286-armv8-cavium-Add-an-implementation-of-PSCI-calling-f.patch \
            file://0287-armv8-cavium-SLT-related-config-changes.patch \
            file://0288-armv8-cavium-Add-the-board-environment-variable.patch \
            file://0289-armv8-cavium-net-Add-VNIC-and-SMI-support.patch \
            file://0290-armv8-cavium-Add-board-specific-VNIC-initialization.patch \
            file://0291-armv8-cavium-Add-an-FDT-for-ThunderX-88xx.patch \
            file://0292-armv8-cavium-Enable-Tab-autocompletion-Disabled-auto.patch \
            file://0293-armv8-cavium-Add-CONFIG_CMD_ATF.patch \
            file://0294-armv8-cavium-Add-SPD-addresses-to-the-config.patch \
            file://0295-armv8-cavium-Add-filesystems-support.patch \
            file://0296-cavium-Add-ATF-accessed-storage-environment.patch \
            file://0297-Board-specific-SATA-support-functions.patch \
            file://0298-armv8-cavium-SATA-related-config-options.patch \
            file://0299-Merged-FDT-patching-code.patch \
            file://0300-Move-FDT-patching-routines-to-the-ft_board_setup-sta.patch \
            file://0301-armv8-cavium-Add-the-vnic-command-for-adding-MAC-add.patch \
            file://0302-armv8-cavium-Add-CONFIG_CMD_VNIC.patch \
            file://0303-VNIC-random-enetaddr-initialization.patch \
            file://0304-Added-MAC-overwrite-config-option.patch \
            file://0305-Added-FDT-pre-boot-setup.patch \
            file://0306-Added-a-DDR3-module-type-string-returning-function.patch \
            file://0307-Added-preliminary-PCI-E-RC-support.patch \
            file://0308-armv8-cavium-Enable-PCIe-support.patch \
            file://0309-Added-SATA-AHCI-block-driver.patch \
            file://0310-SATA-AHCI-cleanup.patch \
            file://0311-Add-I2C-config-support.patch \
            file://0312-Add-network-commands.patch \
            file://0313-Added-environment-saving-command.patch \
            file://0314-Fixup-ethernet-macs-nodeX-property.patch \
            file://0315-Working-PCIe-support.patch \
            file://0316-Fix-config-options.patch \
            file://0317-Add-E1000-support.patch \
            file://0318-Add-10G-modes.patch \
            file://0319-usb-cavium-Add-multi-node-support-for-xHCI.patch \
            file://0320-Multi-node-support-for-SATA.patch \
            file://0321-Add-missing-definitions.patch \
            file://0322-Fix-fdt.c-build-warnings.patch \
            file://0323-Fix-build-warnings.patch \
            file://0324-Merge-fix.patch \
            file://0325-Increase-the-environment-storage-space.patch \
            file://0326-cavium-Add-CPU-specific-reset-function.patch \
            file://0327-cavium-Add-hardware-watchdog-support.patch \
            file://0328-serial-Wait-for-FIFO-to-empty-when-transferring-char.patch \
            file://0329-armv8-add-utility-functions.patch \
            file://0330-armv8-Add-more-CPU-state-information-to-the-show_reg.patch \
            file://0331-cavium-Modify-clock-frequency-property-based-on-exte.patch \
            file://0332-net-e1000-Fix-PHY-reset-check-on-8257x.patch \
            file://0333-cavium-Update-PCI-PCIe-support-for-Pass-2.0.patch \
            file://0334-cavium-Include-CSRs-definitions-unconditionally.patch \
            file://0335-cavium-Initialize-SMI-only-when-enabled-in-the-confi.patch \
            file://0336-cavium-Update-PCIe-config-options.patch \
            file://0337-Add-CSR-include-directory-symlink.patch \
            file://0338-cavium-Fix-PCIe-workaround-for-old-passes.patch \
            file://0339-cavium-vnic-Update-VNIC-for-Pass-2.0.patch \
            file://0340-cavium-Update-random-ethernet-address-generation.patch \
            file://0341-cavium-sata-Update-SATA-support-for-2s-setups.patch \
            file://0342-cavium-Update-FDT-sources.patch \
            file://0343-cavum-vnic-Print-generated-MAC-address-when-it-s-gen.patch \
            file://0344-cvium-Tidy-up-VNIC-related-options.patch \
            file://0345-cavium-Update-boot-support-options.patch \
            file://0346-armv8-cavium-Implement-ARMv8-specific-memory-node-fi.patch \
            file://0347-cavium-vnic-Fix-strict-aliasing-warnings.patch \
            file://0348-cavium-Update-FDT-source-This-commit-includes-range-.patch \
            file://0349-ahci-Remove-arbitrary-timer-initialization-This-migh.patch \
            file://0350-Remove-writeq_relaxed-reference.patch \
            file://0351-Added-EA-register-definitions.patch \
            file://0352-PCI-EA-Add-support-for-future-use.patch \
            file://0353-pci-Rework-initialization.patch \
            file://0354-pci-Rework-Pass-1.0-workarounds.patch \
            file://0355-caium-Update-FDT-source.patch \
            file://0356-cavium-Add-2s-FDT-source.patch \
            file://0357-cavium-Suppress-the-build-warning.patch \
            file://0358-cavium-Suppress-excess-debug-output.patch \
            file://0359-cavium-Update-PCIe-support.patch \
            file://0360-cavium-Add-PEM-definitions-to-the-FDT.patch \
            file://0361-cavium-Add-PEM-entries-patching-support.patch \
            file://0362-pci-Add-PCIe-capability-register-definitions.patch \
            file://0363-cavium-Change-PCIe-bus-address-definitions.patch \
            file://0364-cavium-Update-CPU-addresses-to-match-bus-regions.patch \
            file://0365-cavium-Enable-every-function-enumeration-in-config.patch \
            file://0366-cavium-Add-Node1-memory-ranges.patch \
            file://0367-cavium-Remove-duplicated-config-options.patch \
            file://0368-cavium-Update-FDTs-for-OF-control.patch \
            file://0369-Update-BGX-related-PHY-setup-for-FDT.patch \
            file://0370-Add-ebb8604-board-type-for-setting-up-the-LMAC-count.patch \
            file://0371-cavium-Add-CONFIG_SYS_VSNPRINTF.patch \
            file://0372-cavium-vnic-Fix-RX-queue-handling.patch \
            file://0373-cavium-vnic-Remove-excess-debug-messages.patch \
            file://0374-block-ahci-Fix-sata_reset.patch \
            file://0375-Config-remove-redundant-definitions.patch \
            file://0376-PCI-Check-PEM-link-status.patch \
            file://0377-Fix-rebase-residue.patch \
            file://0378-Thunderx-u-boot-XAUI-fixes.patch \
            file://0379-Thunderx-Fix-for-mac-address-set-in-u-boot-not-refle.patch \
            file://0380-dts-integrate-commit-4ebc7811ca0713cc9478d82f83269f4.patch \
            file://0381-PCIe-Skip-PEM-enumeration.patch \
            file://0382-Read-the-board-type-from-DT-passed-by-BDK.patch \
            file://0383-thunderx-Add-new-defines-to-accomodate-BDK-FDT.patch \
            file://0384-cavium-Add-L2-cache-flush-routine-to-run-at-the-star.patch \
            file://0385-Thunderx-Add-u-boot-support-for-86xx-board.patch \
            file://0386-Increase-the-FDT-size.patch \
            file://0387-ThunderX-Update-config-files.patch \
            file://0388-PCI-DM-Add-capability-support.patch \
            file://0389-PCI-DM-Add-Enhanced-Allocation-support.patch \
            file://0390-cavium-pci-Rework-PCI-support.patch \
            file://0391-cavium-Move-RC-status-checking-code-to-fdt.c.patch \
            file://0392-cavium-Update-ThunderX-configs-for-PCI-ECAM.patch \
            file://0393-sata-Move-to-PCI-based-enumeration.patch \
            file://0394-thunderx-Remove-obsolete-SATA-related-code.patch \
            file://0395-Update-configs.patch \
            file://0396-USB-XHCI-Remove-ThunderX-specific-code.patch \
            file://0397-PCI-DM-Allow-more-that-one-resource-of-the-same-type.patch \
            file://0398-cavium-Update-config-for-xhci-pci-usage.patch \
            file://0399-cavium-Use-FDT-blob-from-ATF.patch \
            file://0400-cavium-Remove-FDT-source-code-from-the-tree.patch \
            file://0401-cavium-Drop-FDT-patching-code-and-remove-the-BDK-con.patch \
            file://0402-cavium-Update-88xx-config-for-generalized-VNIc-relat.patch \
            file://0403-cavium-Drop-non-OF-code.patch \
            file://0404-cavium-Add-81xx-config.patch \
            file://0405-cavium-vnic-Take-the-number-of-BGX-devices-from-the-.patch \
            file://0406-Use-qlm_mode-for-distinguishing-BGX-interfaces.patch \
            file://0407-Configure-lmac_type-for-each-lmacid.patch \
            file://0408-Configure-autoneg-and-arbitration-for-KR-interfaces-.patch \
            file://0409-Fix-compilation-errors.patch \
            file://0410-FDT-Add-fdtdec_get_pci_bus_range-function.patch \
            file://0411-cavium-Add-external-PCIe-support.patch \
            file://0412-Fix-lmac_count-for-XAUI-XLAUI-interface.patch \
            file://0413-Fix-compilation-errors-in-configuration-files.patch \
            file://0414-Fix-the-81xx-config-for-crash-during-sata-init.patch \
            file://0415-net-thunderx-Fix-TL4-configuration-for-secondary-Qse.patch \
            file://0416-net-thunderx-Moved-HW-capability-info-from-macros-to.patch \
            file://0417-net-thunderx-Add-VNIC-s-PCI-devid-on-future-chips.patch \
            file://0418-net-thunderx-Add-support-for-81xx-and-83xx-chips.patch \
            file://0419-net-thunderx-CQE_RX2_S-is-always-enabled-on-future-c.patch \
            file://0420-Enable-hw_tso-for-81xx.patch \
            file://0421-net-thunderx-Check-link-status-at-the-start-of-netwo.patch \
            file://0422-net-thunderx-Fix-initialization-order.patch \
            file://0423-net-thunderx-Additional-parameter-checks.patch \
            file://0424-Don-t-clear-Signed-off-by-Chandrakala-Chavva-cchavva.patch \
            file://0425-Fix-the-link-status-checks-for-10G-40G-interfaces.patch \
            file://0426-Get-lmac_type-from-LMAC0-LMAC2-based-on-the-DLM-used.patch \
            file://0427-Pass-the-correct-phy-address-to-the-interfaces-from-.patch \
            file://0428-Perform-RX-Equalization-to-XFI-XLAUI-RXAUI-interface.patch \
            file://0429-Replace-printfs-with-debug-in-rx_equalization-functi.patch \
            file://0430-Update-BGX_SPUX_STATUS1.rcv_lnk-only-when-the-value-.patch \
            file://0431-net-thunderx-Update-and-fix-Clause45-support.patch \
            file://0432-net-thunderx-Update-link-tatus-check.patch \
            file://0433-net-Add-more-10G-modes-to-the-PHY-library.patch \
            file://0434-net-thunderx-Copy-link-parameters-from-phydev-for-SG.patch \
            file://0435-pci-Do-device-probing-right-after-its-discovery.patch \
            file://0436-i2c-thunderx-Rework-I2C-driver-to-use-PCI-enumeratio.patch \
            file://0437-pci-Add-Cavium-Vendor-ID.patch \
            file://0438-thunderx-Drop-stale-FDT-retrieval-code.patch \
            file://0439-thunderx-Drop-stale-config-options.patch \
            file://0440-thunderx-Update-default-config-for-the-new-I2C-drive.patch \
            file://0441-pci-thunderx-Support-PCIe-switches.patch \
            file://0442-net-thunderx-Fix-lmac-count-for-40G_KR4.patch \
            file://0443-net-thunderx-Fix-get_qlm_for_bgx.patch \
            file://0444-net-thunderx-Added-QSGMII-support.patch \
            file://0445-thunderx-Update-configs-for-DM-USB.patch \
            file://0446-thunderx-Remove-stale-node1-mapping-entries-from-con.patch \
            file://0447-thunderx-Remove-stale-PCI-address-windows-definition.patch \
            file://0448-net-thunderx-Fix-BGX_CMRX_CONFIG-for-QSGMII-mode.patch \
            file://0449-net-thunderx-Fix-lmac-mapping-for-RXAUI-interface.patch \
            file://0450-net-thunderx-Set-disparity-only-for-QSGMII-mode.patch \
            file://0451-gpio-thunderx-Add-ThunderX-GPIO-driver.patch \
            file://0452-gpio-armv8-Fix-includes.patch \
            file://0453-armv8-Add-64-bit-setbit-clrbit-functions-macros.patch \
            file://0454-thunderx-Update-the-config-to-use-the-GPIO-driver.patch \
            file://0455-net-thunderx-Fix-RXAUI-configuration.patch \
            file://0456-mdio-thunderx-Rework-SMI-support-for-DM.patch \
            file://0457-thunderx-Remove-SMI-initialization-from-the-platform.patch \
            file://0458-thunderx-Update-configs-for-SMI-support.patch \
            file://0459-net-thunderx-Defer-PHY-initialization.patch \
            file://0460-Don-t-enable-debugging-by-default.patch \
            file://0461-thunderx-Add-the-refclk-setup-routine-back.patch \
            file://0462-pci-Add-extended-capability-search-functions-for-DM.patch \
            file://0463-pci-Change-dm_pci_map_bar-semantics.patch \
            file://0464-dm-pci-Update-I2C-controllers-for-changes-semantics-.patch \
            file://0465-dm-pci-Update-e1000-for-changed-semantics-Signed-off.patch \
            file://0466-dm-pci-Initial-SRIOV-support.patch \
            file://0467-dm-pci-Change-EA-reading-functions-to-return-BAR-siz.patch \
            file://0468-dm-pci-Return-BAR-size-from-dm_map_bar.patch \
            file://0469-AHCI-Update-AHCI-for-new-dm_map_bar-semantics.patch \
            file://0470-i2c-Update-ThunderX-I2C-for-new-dm_map_bar-semantics.patch \
            file://0471-dm-net-Update-ThunderX-SMI-for-new-dm_map_bar-semant.patch \
            file://0472-net-thunderx-Use-ECAM-based-enumeration-for-VNIC.patch \
            file://0473-cavium-Remove-stale-VNIC-initialization-code.patch \
            file://0474-dm-pci-Set-PF-information-for-VF-devices.patch \
            file://0475-net-cavium-Use-ECAM-based-enumeration-for-BGX.patch \
            file://0476-cavium-Drop-legacy-initialization-code.patch \
            file://0477-dm-pci-Support-VFs-in-dm_pci_map_bar.patch \
            file://0478-net-cavium-Get-subsystem-ID-from-PCI-config-space.patch \
            file://0479-gpio-cavium-Fix-copy-paste-leftovers-Signed-off-by-S.patch \
            file://0480-net-e1000-dm-Fix-DM_NET-build-for-e1000.patch \
            file://0481-thunderx-Parse-BGX-FDT-configs-only-when-the-driver-.patch \
            file://0482-net-cavium-Remove-excess-printf-in-the-VF-initializa.patch \
            file://0483-net-thunderx-Fix-GCC5-build.patch \
            file://0484-cavium-thunderx-Minor-cleanup.patch \
            file://0485-cavium-thunderx-Set-ethaddr-variable-using-parameter.patch \
            file://0486-cavium-Add-DS1337-RTC-support.patch \
            file://0487-Disable-function-tracing-for-e1000-driver.patch \
            file://0488-Hide-printing-NOPs-when-printing-device-tree-if-fdt-.patch \
            file://0489-cavium-Fix-issue-with-UART-clock.patch \
            file://0490-Added-setenv_force-to-override-the-read-only-flag-wh.patch \
            file://0491-Rewrote-the-device-tree-functions-to-use-properties-.patch \
            file://0492-thunderx-mdio-Fix-operation-type-for-SMI-write.patch \
            file://0493-net-thunderx-Fix-88xx-pass2-silicon-check.patch \
            file://0494-net-thunderx-Added-RGMII-support.patch \
            file://0495-net-thunderx-Minor-cleanup.patch \
            file://0496-device-tree-Changed-printf-to-debug.patch \
            file://0497-Fixed-reading-PHY-information-out-of-device-tree.-No.patch \
            file://0498-net-thunderx-Remove-local-printfs.patch \
            file://0499-net-thunderx-Fix-RXAUI-probing.patch \
            file://0500-net-thunder-Add-CONFIG_THUNDER_XCV.patch \
            file://0501-Fix-the-model-string-for-81xx.patch \
            file://0502-Enable-USB-was-removed-from-previous-commits.patch \
            file://0503-Revert-more-local-changes.patch \
            file://0504-Revert-changes-made-to-set-clock-frequency-for-refcl.patch \
            file://0505-booti-arm64-align-kernel-start-address-to-2MB.patch \
            file://0506-net-thunderx-Report-BGX-is-configured-as-XAUI-only-f.patch \
            file://0507-net-thunder-Fix-number-of-lmacs-for-XAUI-interface.patch \
            file://0508-net-thunderx-Fix-typo-in-CONFIG_THUNDERX_XCV-configu.patch \
            file://0509-Fixed-i2c-support-and-added-some-comments-as-well.-N.patch \
            file://0510-Refactored-bootloader-code-to-put-files-in-the-corre.patch \
            file://0511-Moved-thunderx-arch-specific-include-files.patch \
            file://0512-Disabled-debugging-messages.patch \
            file://0513-net-thunderx-Use-Vitesse-PHY-driver-for-QSGMII.patch \
            file://0514-net-thunderx-Fix-number-of-lmacs-for-XLAUI-interface.patch \
            file://0515-usb-xhci-avoid-double-free-ing-device-s-priv-structu.patch \
            file://0516-Print-BGX-and-port-no-when-phy-is-not-present.patch \
            file://0517-net-thunderx-Added-model_id-new-field.patch \
            file://0518-thunderx-Don-t-enable-debugging-by-default.patch \
            file://0519-net-thunderx-Enabled-RGMII-support.patch \
            file://0520-net-thunderx-Fixed-probing-of-DLM0-DLM1-lane1-on-EBB.patch \
            file://0521-net-thunderx-Make-BGX0-restriction-specific-to-alter.patch \
            file://0522-net-thunderx-Fix-number-of-lmacs-to-use-for-RXAUI-in.patch \
            file://0523-net-thunderx-Define-alternate_pkg.patch \
            file://0524-net-thunderx-Fix-compilation-errors.patch \
            file://0525-This-patch-adds-support-for-setting-the-command-prom.patch \
            file://0526-thunderx81xx-env-updated-kernel_addr-to-aligned-addr.patch \
            file://0527-Added-support-for-the-Marvell-PHY.patch \
            file://0528-83xx-adding-board-support-for-83xx.patch \
            file://0529-tx83xx-update-83xx-config-header-file.patch \
            file://0530-tx83-pci-increase-MAX_PCI_REGIONS-to-8.patch \
            file://0531-83xx-bringup-disable-bgx-vnic-and-smi-drivers-till-i.patch \
            file://0532-dm-pci-decode_regions-should-fail-when-hose-region_c.patch \
            file://0533-dm-pci-workaround-SRIOV-NVF-for-ThunderX-8xxx.patch \
            file://0534-83xx-vnic-Add-network-support.patch \
            file://0535-tx83-update-kernel_addr-to-aligned-address.patch \
            file://0536-83xx-bgx-updating-bgx-to-work-with-83xx-interfaces.patch \
            file://0537-83xx-bgx-Wait-for-link-to-be-fully-up-and-stable.patch \
            file://0538-config-83xx-Max-AHCI-SATA-ports-are-6.patch \
            file://0539-83xx-bgx-program-lmac_type-for-all-lmacs.patch \
            file://0540-83xx-bgx-limit-max_lmac-to-2-for-bgx3.patch \
            file://0541-83xx-vnic-bgx-fixed-issues-in-vnic-and-bgx.patch \
            file://0542-83xx-set-MEM_BASE-to-offset-40MB.patch \
            file://0543-Renamed-the-platform-config-files-for-multi-platform.patch \
            file://0544-CSR-Fix-the-CSR_READ-CSR_WRITE-to-match-the-new-csrs.patch \
            file://0545-Check-lmc_mode32-for-returning-the-correct-alternati.patch \
            file://0546-Renamed-tegra-to-thunderx.patch \
            file://0547-Added-functions-for-getting-clock-information.patch \
            file://0548-Added-some-FDT-functions-useful-for-Cavium-SoC-code.patch \
            file://0549-Some-data-structures-will-be-overwritten-if-U-Boot-g.patch \
            file://0550-Minor-cleanup-to-formatting.patch \
            file://0551-Added-myself-as-a-maintainer-for-Cavium-s-ThunderX-O.patch \
            file://0552-Fixed-rst_boot-register-definitions.patch \
            file://0553-Added-Cavium-eMMC-SD-driver-support-to-U-Boot.patch \
            file://0554-Fixed-an-uninitialized-variable-warning.patch \
            file://0555-Fixed-function-definition-by-using-ulong-instead-of-.patch \
            file://0556-Added-clock.c-to-Makefile.patch \
            file://0557-Added-compatibility-with-the-Cavium-driver-which-emu.patch \
            file://0558-Added-MMC-driver-support-for-CN81xx-boards.patch \
            file://0559-Added-missing-configuration-parameter-cap-mmc-highsp.patch \
            file://0560-Check-if-device-is-present-on-PCI-bus-for-probe-and-.patch \
            file://0561-The-ECAM-driver-needs-to-be-able-to-be-loaded-early-.patch \
            file://0562-Fix-GPIO-driver-for-OcteonTX-Thunder.patch \
            file://0563-This-fixes-a-crash-when-a-MMC-SD-device-is-not-plugg.patch \
            file://0564-Fix-a-number-of-issues-with-eMMC-and-adds-some-enhan.patch \
            file://0565-Clarify-what-the-CRC7-displayed-for-mmc-info-is-for.patch \
            file://0566-Added-definition-for-SD-4.0-support.patch \
            file://0567-This-patch-incorporates-a-number-of-additional-fixes.patch \
            file://0568-T83-config-Some-data-structures-will-be-overwritten-.patch \
            file://0569-T83-config-Added-MMC-driver-support-for-CN83xx-board.patch \
            file://0570-Define-CONFIG_FIT-required-for-Mitel.patch \
            file://0571-bgx-Merged-T81-and-T83-changes.patch \
            file://0572-Fixed-power-gpios-device-tree-property-for-the-mmc-s.patch \
            file://0573-Fix-compiler-warning-messages.patch \
            file://0574-Remove-debug-print-was-left-out-from-previous-commit.patch \
            file://0575-Fixes-several-minor-issues-and-adds-debugging-suppor.patch \
            file://0576-Added-support-for-OcteonTX-CN83XX.patch \
            file://0577-Fix-problem-with-GPIO-pins-32-63-due-to-64-bit-regis.patch \
            file://0578-setbits_le64-should-not-be-used-to-set-or-clear-GPIO.patch \
            file://0579-Fixed-order-of-parameters-to-writeq-fixes-GPIO-not-w.patch \
            file://0580-Enable-some-usb-to-ethernet-dongles.patch \
            file://0581-Use-the-GPIO_CONST-register-to-determine-the-number-.patch \
            file://0582-cavium-nic-zero-malloc-d-memory.patch \
            file://0583-Configure-ARQ107-PHY.patch \
            file://0584-Fix-some-comments.patch \
            file://0585-rtc-ds1337-add-support-for-driver-model.patch \
            file://0586-configs-thunderx_81xx-remove-RTC-config-items.patch \
            file://0587-drivers-spi-add-support-for-thunderx-spi-controller.patch \
            file://0588-configs-thunderx_81xx-add-spi-related-config-items.patch \
            file://0589-configs-add-SF-command-support.patch \
            file://0590-cmd-bootimgup-new-command-to-update-boot-image.patch \
            file://0591-configs-thunderx_81xx-add-bootimgup-config-item.patch \
            file://0592-sata-Cast-to-proper-size-to-read-SATA-disks-greater-.patch \
            file://0593-cmd-bootimgup-use-default-offset-as-0.patch \
            file://0594-board-thunderx-remove-atf-commands-from-uboot.patch \
            file://0595-cmd-bootimgup-validate-boot-image-before-update.patch \
            file://0596-cmd-bootimgup-clear-checkpatch-errors.patch \
            file://0597-bgx-fix-for-dhcp-not-working-for-sgmii-interface-wit.patch \
            file://0598-bgx-fix-for-rgmii-broken-by-previous-commit.patch \
            file://0599-configs-thunderx_83xx-add-SF-SPI-and-bootimgup-suppo.patch \
            file://0600-bgx-remove-hardcoded-values.patch \
            file://0601-bgx-xaui-fix.patch \
            file://0602-Define-CONFIG_SPI_FLASH_MACRONIX-as-NAS-board-has-MX.patch \
            file://0603-BGX-Hack-to-configure-QSGMII-on-Router-board.patch \
            file://0604-cmd-bootimgup-update-image-support-for-mmc-device.patch \
            file://0605-bgx-update-the-driver-to-read-the-PHY-info-from-OS-D.patch \
            file://0606-Disable-RTL8169-define-till-driver-is-fixed.patch \
            file://0607-configs-thunderx_81xx-remove-NOR-flash-defines.patch \
            file://0608-drivers-rtc-fix-devicetree-compiler-warning.patch \
            file://0609-bgx-remove-resetting-the-qlm.patch \
            file://0610-cmd-bootimgup-update-description.patch \
            file://0611-Configure-only-one-lmac-for-aqr107-interface.patch \
            file://0612-cmd-bootimgup-update-fat-entry-of-boot-image.patch \
            file://0613-cmd-bootimgup-modify-description.patch \
            file://0614-Fix-compilation-warnings.patch \
            file://0615-env-sf-add-support-environment-storage-in-SPI-flash.patch \
            file://0616-configs-thunderx_81-83-remove-re-definition-CONFIG_A.patch \
            file://0617-BGX-Fix-the-order-of-parameters-passed-to-writeq.patch \
            file://0618-cmd-bootimgup-fix-issues-with-arguments.patch \
            file://0619-board-cavium-fix-ethaddr-environment-variables.patch \
            file://0620-env-sf-use-board_early_init_r-to-fix-crash.patch \
            file://0621-board-cavium-increment-env-index-properly.patch \
            file://0622-BGX-Fix-RGMII-interface.patch \
            file://0623-BGX-Fix-max_lanes-for-a-given-qlm-dlm-to-apply-rx-eq.patch \
            file://0624-thunderx_ecam-add-support-for-83xx.patch \
            file://0625-USB-2.0-Added-additional-delay.patch \
            file://0626-drivers-spi-remove-static-pci-probe.patch \
            file://0627-drivers-mmc-remove-pci-static-probe.patch \
            file://0628-drivers-i2c-remove-static-pci-probe.patch \
            file://0629-drivers-net-cavium-remove-static-pci-probe.patch \
            file://0630-drivers-net-cavium-remove-static-pci-probe.patch \
            file://0631-drivers-net-cavium-modify-smi-driver-to-driver-model.patch \
            file://0632-drivers-net-cavium-add-support-for-marvell-88x3120-p.patch \
            file://0633-drivers-net-bgx-fix-83xx-crash.patch \
            file://0634-drivers-sync-with-compatibles-in-dts-files.patch \
            file://0635-BGX-Fix-QSGMII-on-T81-alternative-package.patch \
            file://0636-Enable-Micronix-SPI-flash-for-T83.patch \
            file://0637-Changed-mmc-driver-to-use-updated-device-tree-power-.patch \
            file://0638-This-fixes-some-additional-issues-with-the-new-MMC-d.patch \
            file://0639-Addresses-below-40M-are-reserved-on-T83.patch \
            file://0640-drivers-i2c-send-nack-at-end-of-read-op.patch \
            file://0641-Fix-wp-inverted-and-the-handling-of-wp-gpios-and-cd-.patch \
            file://0642-Fixed-minor-compiler-warnings.patch \
            file://0643-Fixed-minor-compile-warning.patch \
            file://0644-driver-net-Configure-only-one-interface-in-each-bgx-.patch \
            file://0645-fdt-Workaround-FDT-base-address-passing-from-ATF-to-.patch \
            file://0646-arm-config-Enable-alignment-of-FDT-base-address.patch \
            file://0647-netdev-octeontx-Program-BGXX_SPUX_AD_ADV-CSR-properl.patch \
            file://0648-Allow-boards-to-initialize-the-DT-at-runtime.patch \
            file://0649-board-cavium-Get-FDT-base-address-from-ATF.patch \
            file://0650-Revert-FDT-Workaround-to-pass-FDT-base-address-to-U-.patch \
            file://0651-arch-thunderx-Drop-SMC-call-THUNDERX_FDT_GET.patch \
            file://0652-build-t93-Add-default-config-for-t93.patch \
            file://0653-configs-add-initial-support-for-cn93xx.patch \
            file://0654-configs-93xx-limit-cpu-count-to-1.patch \
            file://0655-configs-93xx-use-spi-flash-as-env-storage.patch \
            file://0656-board-thunderx-enable-board-early-init-config-item.patch \
            file://0657-mmc-Don-t-power-down-each-mmc-device.patch \
            file://0658-mmc-Don-t-invert-cd-gpios-and-wp-gpios-value.patch \
            file://0659-config-kconfig-changes-for-t81-83-93.patch \
            file://0660-armv8-thunderx-Remove-obsolete-L2C-cleanup-code.patch \
            file://0661-NVMe-add-NVMe-driver-support.patch \
            file://0662-NVMe-add-nvme-commands.patch \
            file://0663-nvme-Properly-use-the-PCI-subsystem.patch \
            file://0664-armv8-cavium-Update-T83-default-config.patch \
            file://0665-nvme-Use-the-lbaint_t-type-for-blknr-parameter.patch \
            file://0666-Kconfig-Add-CONFIG_SATA-to-enable-SATA.patch \
            file://0667-ahci-Support-wider-range-of-AHCI-controllers-Support.patch \
            file://0668-cavium-thunderx-Enable-PCI-based-SCSI-AHCI-driver.patch \
            file://0669-ahci-Alias-SCSI-and-SATA-for-AHCI.patch \
            file://0670-nvme-Add-legacy-API-support.patch \
            file://0671-cavium-Add-CONFIG_SYS_NVME_MAX_DEVICE-definition.patch \
            file://0672-thunderx-Update-T81-config-for-the-new-block-devices.patch \
            file://0673-drivers-thunder_gpio-store-desc-offset-while-xlate.patch \
            file://0674-drivers-mmc-adapt-cavium-driver-to-latest-upstream-c.patch \
            file://0675-cmd-mmc-adapt-to-new-cavium-mmc-driver-changes.patch \
            file://0676-cmd-bootimgup-update-with-latest-block-layer.patch \
            file://0677-configs-more-kconfig-changes.patch \
            file://0678-board-thunderx-cleanup-dram_init.patch \
            file://0679-arch-arm-cache_v8-use-debug-macro-to-disable-huge-pr.patch \
            file://0680-mach-thunderx-remove-call-to-dram-size.patch \
            file://0681-configs-fdt-cleanup.patch \
            file://0682-board-cavium-remove-use-of-CPU_RELEASE_ADDR.patch \
            file://0683-BGX-Remove-board-specific-changes.patch \
            file://0684-board-thunderx-use-correct-order-of-args-for-fdt_eac.patch \
            file://0685-drivers-i2c-use-read-flag-instead-of-write-in-probe_.patch \
            file://0686-board-thunderx-call-bgx-phy-device-tree-parsing-in-b.patch \
            file://0687-configs-93xx-use-OF_BOARD-to-get-device-tree.patch \
            file://0688-board-thunderx-temp-fix-to-read-board-model-again.patch \
            file://0689-Enable-PCIe-to-be-initialized-before-the-environment.patch \
            file://0690-Fixes-calls-to-mmc_get_blk_desc-to-include-the-devic.patch \
            file://0691-Add-support-disabled-for-storing-the-environment-in-.patch \
            file://0692-Reduce-TFTP-hash-output-to-behave-like-Octeon.patch \
            file://0693-spi-add-support-of-SPI-flash-commands.patch \
            file://0694-configs-83xx-add-support-for-FLASH_4BAIS.patch \
            file://0695-configs-83xx-add-support-for-realtek-usb-ethernet-ad.patch \
            file://0696-nvme-Print-NVMe-line-only-when-NVME-devices-are-pres.patch \
            file://0697-ata-ahci-Only-dump-controller-caps-in-debug-builds.patch \
            file://0698-ata-achi-Only-print-spinup-and-link-timeout-messages.patch \
            file://0699-cmd-Add-init-subcommand-as-a-synonym-for-scan-to-the.patch \
            file://0700-board-thunderx-set-ethaddr-environment-variables-cor.patch \
            file://0701-t93-update-maxcpus-24-to-support-multi-core-booting.patch \
            file://0702-drivers-net-cavium-bgx-fix-logic-error-in-xaui-init.patch \
            file://0703-drivers-mmc-change-device-in-mmc_select_hwpart.patch \
            file://0704-drivers-rtc-fix-ds1337-century-base-to-2000.patch \
            file://0705-board-thunderx-remove-redundant-code.patch \
            file://0706-drivers-ahci-mark-message-as-debug.patch \
            file://0707-Increase-the-size-of-the-maximum-image-supported-by-.patch \
            file://0708-configs-83xx-remove-multiple-definition-of-CONFIG_SY.patch \
            file://0709-drivers-net-bgx-add-remove-function-code.patch \
            file://0710-board-thunderx-handle-interface-config-changes-for-e.patch \
            file://0711-Increase-maximum-size-of-FIT-images-supported-for-bo.patch \
            file://0712-Allow-DHCP-server-to-specify-tftp-server-address.patch \
            file://0713-Fix-warnings-on-bootm-size-and-allow-DHCP-server-to-.patch \
            file://0714-BGX-driver-Fix-RX-equalization-for-XLAUI-interface.patch \
            file://0715-BGX-Print-only-valid-BGX-configurations.patch \
            file://0716-BGX-Fix-snprintf-call-in-previous-commit.patch \
            file://0717-configs-93xx-Move-CONFIG_SYS_TEXT_BASE-to-32M.patch \
            file://0718-BGX-Disable-PCS-and-power-down-BGX-before-booting-ke.patch \
            file://0719-configs-81xx-add-support-for-storing-environment-in-.patch \
            file://0720-fdt-Check-for-NULL-return-from-fdt_getprop-in-fdt-se.patch \
            file://0721-fdt-fix-prop-.-not-found-error-in-fdt-set-command.patch \
            file://0722-drivers-pci-clear-bar_response-before-fetch-of-upper.patch \
            file://0723-fdt-Check-for-NULL-return-from-fdt_getprop-in-fdt-se.patch \
            file://0724-fdt-fix-prop-.-not-found-error-in-fdt-set-command.patch \
            file://0725-configs-93xx-Move-CONFIG_SYS_TEXT_BASE-to-64M.patch \
            file://0726-Remove-BGX-defines-from-T93.patch \
            file://0727-configs-81xx-add-support-for-FLASH_4BAIS.patch \
            file://0728-configs-93xx-add-support-for-FLASH_4BAIS.patch \
            file://0729-configs-t93-remove-EFI_HELLO_WORLD-example-efi-app.patch \
            file://0730-configs-t81-83-remove-EFI_HELLO_WORLD-example-efi-ap.patch \
            file://0731-Cavium-T81-SPI-Enabled-support-for-32-bit-SPI-flash.patch \
            file://0732-Cavium-T81-RTC-Enable-support-for-DS1307-compatible-.patch \
            file://0733-env-rename-old-env-api-to-new-in-all-files.patch \
            file://0734-nvme-sync-with-code-in-v2018.01.patch \
            file://0735-BGX-Fix-QLM-configuration-for-alternative-package.patch \
            file://0736-BGX-Fix-lane_to_sds-for-QSGMII-when-connected-to-QLM.patch \
            file://0737-Obtain-partition-information-from-block-descriptor-i.patch \
            file://0738-partitioning-and-enhanded-user-support-and-BKOPS.patch \
            file://0739-Enable-BOOT-RPMB-and-BKOPS-support-for-T81-T83.patch \
            file://0740-BGX-Adjust-lane_to_sds-based-on-BGX-ENABLE.-macro.patch \
            file://0741-ahci-limit-max-scsi-id-based-on-supported-ports-in-c.patch \
            file://0742-thunderx-remove-unnecessary-files.patch \
            file://0743-Kconfig-add-entries-for-drivers.patch \
            file://0744-Kconfig-more-cleanup-in-thunderx-arch-board-files.patch \
            file://0745-configs-t81-move-to-Kconfig-defines-and-cleanup.patch \
            file://0746-thunderx-remove-stale-atf-svc-calls.patch \
            file://0747-thunderx-clk-defines-from-config-files-moved-to-head.patch \
            file://0748-thunderx-more-code-cleanup.patch \
            file://0749-configs-t83-move-to-Kconfig-defines-and-cleanup.patch \
            file://0750-configs-t93-move-to-Kconfig-defines-and-cleanup.patch \
            file://0751-configs-t93-remove-EFI_HELLO_WORLD-example-efi-app.patch \
            file://0752-configs-t81-83-remove-EFI_HELLO_WORLD-example-efi-ap.patch \
            file://0753-Cavium-T81-RTC-Enable-support-for-DS1307-compatible-.patch \
            file://0754-Enable-BOOT-RPMB-and-BKOPS-support-for-T81-T83.patch \
            file://0755-configs-Remove-CONFIG_SYS_MEM_TOP_HIDE-not-required-.patch \
            file://0756-drivers-smi-update-data-type-for-rd-wr-data-regs.patch \
            file://0757-Remove-multiple-definition-of-CONFIG_SPI_FLASH_4BAIS.patch \
            file://0758-drivers-ahci-fix-delay-in-bootup-for-sff8104-nas8104.patch \
            file://0759-ahci-update-cmd_tbl-and-rx_fis-to-64-bit.patch \
            file://0760-configs-replace-kernel_addr-with-loadaddr-env-variab.patch \
            file://0761-drivers-ahci-ignore-case-on-board-strings-sff-nas810.patch \
            file://0762-cavm-get-rid-of-csr-headers-and-minor-cleanup-in-boa.patch \
            file://0763-cavm-move-usage-from-thunder-to-octeontx-across-code.patch \
            file://0764-cavm-move-93xx-code-to-octeontx2.patch \
            file://0765-board-octeontx-tx2-provide-target-choice-based-on-ar.patch \
            file://0766-mmc-Fix-typo-in-cavium-dat-clk-skew.patch \
            file://0767-configs-enable-autoboot-missed-while-kconfig-cleanup.patch \
            file://0768-drivers-blk-skip-rename-of-scsi-interface-name-to-sa.patch \
            file://0769-f95-add-F95-platform-config.patch \
            file://0770-BGX-Fix-QSGMII-configuration.patch \
            file://0771-Enable-WINBOND-SPI-devices-in-OcteonTX-and-OcteonTX-.patch \
            file://0772-drivers-net-octeontx2-add-initial-code-for-cgx.patch \
            file://0773-board-octeontx2-move-cgx_intf_shutdown-to-board-clea.patch \
            file://0774-board-octeontx2-use-correct-chip-reset-register-and-.patch \
            file://0775-Disable-vsc8531-MSCC-driver.patch \
            file://0776-Disable-vsc8531-MSCC-driver-even-for-T83.patch \
            file://0777-octeontx2-Add-SMC-call-to-disable-RVU-LF-and-PF.patch \
            file://0778-OCTEONTX2-Renamed-t93-as-t96.patch \
            file://0779-drivers-usb-eth-display-interface-name.patch \
            file://0780-Minor-cleanup.patch \
            file://0781-drivers-usb-eth-Fix-displaying-the-interface-name.patch \
            file://0782-BGX-Fix-QSGMII-configuration-when-connected-to-DLM6.patch \
            file://0783-Signed-off-by-Aaron-Williams-aaron.williams-cavium.c.patch \
            file://0784-fs-ext4-Disable-invalid-assert-and-add-support-for-a.patch \
            file://0785-Enable-md5sum-and-sha1sum-commands.patch \
            file://0786-ext4-fix-endian-issue-with-inode-count.patch \
            file://0787-cmd-bootimgup-validate-args-before-update-and-fix-he.patch \
            file://0788-octeontx-nand-Added-nand-and-bch-drivers-for-OcteonT.patch \
            file://0789-octeontx-mtd-nand-Don-t-display-errors-when-NAND-dev.patch \
            file://0790-octeontx-nand-fix-missing-function-prototype-warning.patch \
            file://0791-octeontx-mmc-Rename-cavium_mmc-to-octeontx_mmc-and-u.patch \
            file://0792-octeontx-mmc-Forgot-to-check-in-updated-header-file.patch \
            file://0793-mmc-octeontx-commented-out-defines-that-overlap-with.patch \
            file://0794-mmc-octeontx-octeontx2-Added-octeontx2-support.patch \
            file://0795-octeontx2-mmc-Disable-tap-calibration-in-ASIM.patch \
            file://0796-drivers-pci-remove-auto-probe-of-enumerated-pci-devi.patch \
            file://0797-octeontx-nic-move-to-u-boot-driver-model-for-etherne.patch \
            file://0798-drivers-net-octeontx2-create-files-for-cgx-interface.patch \
            file://0799-Initial-commit-of-nix-registers.patch \
            file://0800-Cavium-Ethernet-NIX-Added-missing-structures-and-reg.patch \
            file://0801-Cavium-Ethernet-NIX.patch \
            file://0802-Updated-registers.patch \
            file://0803-drivers-net-octeontx2-add-initial-code-for-rvu-af-pf.patch \
            file://0804-net-Cavium-NIX-Initial-checkin-of-generated-CSR-file.patch \
            file://0805-drivers-net-octeontx2-few-more-changes-to-code-for-c.patch \
            file://0806-Signed-off-by-Aaron-Williams-aaron.williams-cavium.c.patch \
            file://0807-Signed-off-by-Aaron-Williams-aaron.williams-cavium.c.patch \
            file://0808-OcteonTX2-net-nix-Initial-checkin.patch \
            file://0809-Did-not-mean-to-check-in-these-files.patch \
            file://0810-net-octeontx2-nix-Makefile-change.patch \
            file://0811-drivers-net-octeontx2-update-csr-headers-06-19.patch \
            file://0812-drivers-net-octeontx2-initial-working-checkin-for-NI.patch \
            file://0813-net-octeontx2-check-for-link-status-before-packet-tr.patch \
            file://0814-net-octeontx2-fix-smq-to-send-queue-mismatch-error.patch \
            file://0815-net-octeontx2-fix-dev-name-to-include-sequence-numbe.patch \
            file://0816-net-octeontx2-cgx_intf-skip-error-check-for-shutdown.patch \
            file://0817-net-octeontx2-add-lf-af-shutdown-functions-for-nix-a.patch \
            file://0818-board-octeontx2-include-rvu-cgx-teardown-in-board_qu.patch \
            file://0819-net-octeontx2-cgx_intf-always-clear-overflow-interru.patch \
            file://0820-drivers-net-octeontx2-update-csrs-to-latest.patch \
            file://0821-octeontx-board-and-drivers-use-correct-location-for-.patch \
            file://0822-drivers-mmc-make-changes-for-new-config-defines.patch \
            file://0823-octeontx-octeontx2-cleanup-board-files.patch \
            file://0824-octeontx-tx2-discard-usage-of-soft-reset-register.patch \
            file://0825-octeontx-tx2-move-from-cavium-to-marvell.patch \
            file://0826-octeontx-octeontx2-update-license-headers-across-cod.patch \
            file://0827-common-fix-compile-warning.patch \
            file://0828-drivers-usb-fix-incorrect-bar-number-for-xhci-pci.patch \
            file://0829-octeontx-svc-change-id-of-SMC-calls.patch \
            file://0830-drivers-net-octeontx2-update-cgx-interface-changes.patch \
            file://0831-board-octeontx-fix-ethaddr-cleanup-errors.patch \
            file://0832-Rename-bdk_magic-header-from-THUNDERX-to-OCTEONTX.patch \
            file://0833-drivers-net-octeontx2-fix-min-packet-length-for-RX.patch \
            file://0834-drivers-net-octeontx2-fix-typo-in-cgx-firmware-versi.patch \
            file://0835-mtd-mtdparts-Fix-a-crash-that-occurs-if-mtdparts-mtd.patch \
            file://0836-octeontx-mtd-Add-mtd-partitioning-support.patch \
            file://0837-drivers-mmc-octeontx-add-errata-on-calibration-delay.patch \
            file://0838-drivers-net-octeontx2-code-changes-with-emulator-tes.patch \
            file://0839-octeontx-nand-fix-the-PCI-class-id.patch \
            file://0840-PULL-Fix-compilation-issues.patch \
            file://0841-fix-mmc-recover-the-mainline-mmc-API.patch \
            file://0842-mmc-fix-the-config-name-of-octeontx-driver.patch \
            file://0843-net-octeontx2-sync-up-latest-csr-headers.patch \
            file://0844-drivers-spi-add-non-legacy-support-for-9xx-chips.patch \
            file://0845-drivers-spi-add-flash-arbitration-logic-for-9xx-chip.patch \
            file://0846-cmd-bootimgup-add-support-for-spi-bus-cs-and-mmc-dev.patch \
            file://0847-octeontx2-mmc-update-max-card-slot-count-for-9xx.patch \
            file://0848-octeontx-mmc-Added-timing-support-for-OcteonTX2.patch \
            file://0849-drivers-mmc-fix-typo-with-previous-commit.patch \
            file://0850-net-octeontx2-Fix-for-hw-errata-on-BLK_RST.rst-bit.patch \
            file://0851-drivers-net-octeontx2-disable-NET_OCTEONTX2-and-deco.patch \
            file://0852-drivers-pci-add-support-for-pem-in-9xx.patch \
            file://0853-octeontx2-increase-mmap-region-to-include-PEM-contro.patch \
            file://0854-pci-octeontx2-Workaround-for-PEM-config-space-writes.patch \
            file://0855-96xx-configs-add-i2c-multiplexer-support.patch \
            file://0856-Use-100KHz-for-tclk-on-T9x-SOC.patch \
            file://0857-net-octeontx2-add-smi-driver-for-mdio-bus.patch \
            file://0858-96xx-configs-add-marvell-vitesse-phy-support.patch \
            file://0859-octeontx2-96xx-use-misc_init_r-for-smi-driver-probe.patch \
            file://0860-net-octeontx2-Use-correct-field-to-print-errcode.patch \
            file://0861-drivers-pci-octeontx2-stub-out-pem-resource-access-f.patch \
            file://0862-net-octeontx2-clear-async-events-before-next-cgx-int.patch \
            file://0863-mmc-octeontx-Updated-cn96xx-support.patch \
            file://0864-mmc-octeontx-octeontx2-Fix-obtaining-bus-width-from-.patch \
            file://0865-net-octeontx2-add-remove-handler-to-clear-mac-filter.patch \
            file://0866-t96-config-Enable-e1000-driver.patch \
            file://0867-ahci-program-upper-32bit-for-required-registers.patch \
            file://0868-drivers-pci-octeontx-enable-ras-injection-errata-for.patch \
            file://0869-configs-t96-Enable-USB-to-ethernet-dongles.patch \
            file://0870-configs-t96-Enable-NVME-driver.patch \
            file://0871-configs-96xx-add-DS1337-rtc-support.patch \
            file://0872-drivers-net-fix-issue-with-invalid-mac-address-from-.patch \
            file://0873-board-octeontx2-cleanup-ethaddr-variables.patch \
            file://0874-drivers-spi-add-x4-bus-width-support.patch \
            file://0875-drivers-i2c-mask-read-flag-in-probe_chip.patch \
            file://0876-board-octeontx2-add-missing-kconfig-entry-for-95xx.patch \
            file://0877-drivers-spi-add-check-on-clk-divider-and-dual-mode-s.patch \
            file://0878-drivers-net-octeontx2-sync-csr-headers-as-of-2-4-19.patch \
            file://0879-drivers-i2c-octeontx-cleanup-clock-divider-logic.patch \
            file://0880-drivers-net-octeontx2-clean-up-link-error-messages.patch \
            file://0881-env-sf-add-support-for-fio-spi1-env-with-fdt-string.patch \
            file://0882-configs-octeontx2_95xx-define-misc_init_r-config-ent.patch \
            file://0883-drivers-net-octeontx-de-couple-smi-driver-and-create.patch \
            file://0884-board-octeontx-tx2-use-_check-variant-for-misc-devic.patch \
            file://0885-drivers-net-octeontx2-add-entry-for-80G-speed.patch \
            file://0886-mmc-remove-octeontx-mmc-hacks.patch \
            file://0887-gpio-add-generic-i2c-gpio-driver.patch \
            file://0888-octeontx-octeontx2-use-strlcpy-instead-of-strncpy.patch \
            file://0889-octeontx-octeontx2-Enable-md5sum-and-sha1sum.patch \
            file://0890-mmc-remove-hacks-for-old-OcteonTX-MMC-driver.patch \
            file://0891-octeontx2-mmc-Add-new-octeontx2-mmc-driver.patch \
            file://0892-mmc-octeontx-octeontx2-move-to-new-mmc-driver.patch \
            file://0893-octeontx-bootimgup-Allow-command-for-SPI-NOR.patch \
            file://0894-driver-mmc-octeontx-Fix-compilation-errors.patch \
            file://0895-configs-cn96xx-Enable-mmc-driver.patch \
            file://0896-mmc-octeontx-Don-t-enable-write-protect-by-default.patch \
            file://0897-mmc-octeontx-Remove-old-driver.patch \
            file://0898-configs-Enable-necessary-configuration-for-MMC-to-wo.patch \
            file://0899-driver-mmc-Fix-typo-in-bdk-node-for-getting-board-in.patch \
            file://0900-octeontx2-fix-u-boot-config-check-errors.patch \
            file://0901-driver-net-octeontx-Add-1000Base-X-support.patch \
            file://0902-board-octeontx2-Enable-disable-Out-of-Order.patch \
            file://0903-drivers-net-octeontx2-move-link-bringup-from-boot-to.patch \
            file://0904-octeontx-gpio-clear-pin_xor-bit-when-setting-as-inpu.patch \
            file://0905-Fix-MMC-support-in-ASIM-and-add-emulator-support.patch \
            file://0906-marvell-octeontx2-adding-fail-safe-commands.patch \
            file://0907-cmd-marvell-fix-compile-and-kconfig-errors.patch \
            file://0908-configs-95xx-sync-mmc-config-options-from-96xx.patch \
            file://0909-drivers-mmc-octeontx-skip-calibrate_delay-for-F95-A0.patch \
            file://0910-configs-95xx-enable-RTC-support.patch \
            file://0911-marvell-octeontx2-Disable-failsafe-feature-temporari.patch \
            file://0912-octeontx-mmc-Don-t-do-tuning-in-asim.patch \
            file://0913-mmc-octeontx2-CNF95XX-Fix-timing-taps.patch \
            file://0914-configs-octeontx2_96xx-update-bootargs-to-use-mmc-fo.patch \
            file://0915-octeontx2-decouple-arch-and-board-configurations.patch \
            file://0916-mmc-octeontx-Skip-calibration-check-on-broken-hw.patch \
            file://0917-mmc-octeontx-Make-sure-timing-is-set.patch \
            file://0918-mmc-Don-t-print-error-when-probe-returns-ENODEV.patch \
            file://0919-mmc-export-power-initialization.patch \
            file://0920-mmc-octeontx2-Allow-device-tree-to-set-taps.patch \
            file://0921-mmc-octeontx-Remove-redundant-code.patch \
            file://0922-octeontx-mmc-Make-driver-honor-status-in-devtree.patch \
            file://0923-gpio-i2c_gpio-octeontx_gpio-Use-device-tree-status-f.patch \
            file://0924-board-octeontx2-add-Loki-platform-support.patch \
            file://0925-octeontx2-Fix-warning.patch \
            file://0926-mmc-octeontx2-Add-missing-OcteonTX2-bits.patch \
            file://0927-mmc-octeontx2-Clean-up-watchdog.patch \
            file://0928-mmc-octeontx-Fix-calibration-and-clock-issues.patch \
            file://0929-Fix-timing-issue.patch \
            file://0930-mmc-octeontx-Enable-I-O-power-control.patch \
            file://0931-octeontx-octeontx2-Enable-time-command.patch \
            file://0932-mmc-octeontx-Remove-debug-message.patch \
            file://0933-mmc-octeontx-Allow-tuning-override.patch \
            file://0934-mmc-octeontx-Change-default-timing-taps.patch \
            file://0935-octeontx-serial-Added-pci-bootcmd-input-driver.patch \
            file://0936-cmd-marvell-add-eth-commands-to-set-or-get-fec-phymo.patch \
            file://0937-Removed-space.patch \
            file://0938-board-octeontx2-Fix-issue-with-roll-over-of-MAC-addr.patch \
            file://0939-cmd-eth_cmds-Return-usage-for-invalid-argument-value.patch \
            file://0940-usb-xhci-octeontx2-Fix-RX-issue-with-short-packets.patch \
            file://0941-marvell-octeontx2-Reenable-failsafe-feature.patch \
            file://0942-drivers-net-octeontx-handle-multiple-ring-buffers-in.patch \
            file://0943-serial-Fix-warnings.patch \
            file://0944-board-octeontx2-add-t98-platform-support.patch \
            file://0945-mmc-octeontx2-Fix-numerous-issues.patch \
            file://0946-cmd-marvell-Add-mdio_dbg-command-support.patch \
            file://0947-board-octeontx2-octeontx-bootargs-without-debug.patch \
            file://0948-xhci-octeontx2-Work-around-designware-USB-issue.patch \
            file://0949-drivers-net-octeontx2-print-active-fec-type-for-get_.patch \
            file://0950-mmc-octeontx-Fix-HS400-writes-and-other-issues.patch \
            file://0951-drivers-net-octeontx2-cgx-Accept-broadcast-packets.patch \
            file://0952-octeontx-mmc-Fix-multi-line-comments.patch \
            file://0953-octeontx2-cgx-Implement-command-to-call-SERDES-diagn.patch \
            file://0954-octeontx-bootimgup-Add-support-to-skip-SCP-ROM.patch \
            file://0955-drivers-net-octeontx2-move-to-NPA-buffers-for-trasmi.patch \
            file://0956-spi-octeontx-Clean-up-driver.patch \
            file://0957-spi-octeontx-Add-delay-after-updating-cfg-register.patch \
            file://0958-Renamed-module-octeontx2_cmds.c-octeontx2_failsafe_c.patch \
            file://0959-octeontx2-pci-bootcmd-CLI-does-not-accept-input-from.patch \
            file://0960-Added-support-for-attest-command-for-Software-Attest.patch \
            file://0961-octeontx-octeontx2-cleanup-code-for-upstream.patch \
            file://0962-drivers-net-octeontx2-Fix-stack-corruption-in-nix_lf.patch \
            file://0963-octeontx-octeontx2-config-cleanup.patch \
            file://0964-octeontx-octeontx2-cleanup-pci-code-for-upstream.patch \
            file://0965-drivers-pci-add-map_bar-support-for-Enhanced-Allocat.patch \
            file://0966-octeontx-octeontx2-more-cleanup-for-upstream.patch \
            file://0967-octeontx-mmc-Change-max-sector-count-to-8192.patch \
            file://0968-board-octeontx2-fix-incorrect-mac_addr-initialize.patch \
            file://0969-configs-octeontx2_96xx-enabled-support-for-attest-co.patch \
            file://0970-otx-otx2-Export-board-manufacturing-data-to-env.patch \
            file://0971-octeontx-bootimgup-Numerous-fixes-including-preservi.patch \
            file://0972-octeontx-Move-bootimgup-to-marvell-command-directory.patch \
            file://0973-cmd-attest-add-FIT-image-kernel-ID-support-to-Softwa.patch \
            file://0974-octeontx-Add-PCIe-console.patch \
            file://0975-cmd-eth_cmds-add-support-for-mode-change.patch \
            file://0976-board-octeontx-fix-compiler-warning.patch \
            file://0977-smc-attest-add-conditional-guard-around-SMC-attestat.patch \
            file://0978-cmd-marvell-Enable-bootimgup-command-for-CONFIG_ARCH.patch \
            file://0979-octeontx-octeontx2-increase-CONFIG_SYS_SCSI_MAX_SCSI.patch \
            file://0980-configs-96xx-remove-duplicate-entries.patch \
            file://0981-drivers-i2c-octeontx-fix-incorrect-tclk-calculation.patch \
            file://0982-octeontx-pci-console-Fix-padding-in-data-structure.patch \
            file://0983-octeontx2-pci-console-pci-bootcmd-Don-t-keep-adding-.patch \
            file://0984-drivers-watchdog-add-reset-support-for-OcteonTX.patch \
            file://0985-drivers-spi-octeontx-add-spi_mem-layer-support.patch \
            file://0986-arch-octeontx-tx2-move-dram-region-map-to-dynamic.patch \
            file://0987-drivers-ata-ahci-update-max-id-if-it-is-more-than-av.patch \
            file://0988-drivers-pci-octeontx-rename-pci_octeontx_ecam-to-pci.patch \
            file://0989-drivers-pci-uclass-clean-up-code-after-rebasing-octe.patch \
            file://0990-drivers-pci-uclass-Add-support-for-Alternate-Routing.patch \
            file://0991-drivers-rtc-ds1337-clean-up-dm-support-wrt-checkpatc.patch \
            file://0992-octeontx-octeontx-code-cleanup-after-rebase-from-v20.patch \
            file://0993-board-Marvell-octeontx2-replace-misc_init_r-call.patch \
            file://0994-configs-octeontx-octeontx2-syncup-latest-defconfig.patch \
            file://0995-fdt-replace-cavium-bdk-node-with-another-one.patch \
            file://0996-driver-spi-octeontx-Set-tritx-by-default.patch \
            file://0997-spi-kirkwood-prevent-configuring-speed-exceeding-max.patch \
            file://0998-spi-mvebu_a3700_spi-prevent-configuring-speed-exceed.patch \
            file://0999-arm64-mvebu-a8k-config-add-sar-support-to-ocp-platfo.patch \
            file://1000-arm64-mvebu-common-fix-ramdisk-address.patch \
            file://1001-arm64-mvebu-a8k-config-add-kirkwood-spi-support.patch \
            file://1002-arm64-dts-a8k-add-spi-direct-access-mapping.patch \
            file://1003-arm64-dts-a8k-change-ocp-eth1-mode-to-sgmii.patch \
            file://1004-configs-update-mvebu_ocp-88f8040_defconfig.patch \
            file://1005-drivers-net-octeontx2-add-get_mode-command-support.patch \
            file://1006-board-octeontx-save-board-variables-only-if-changed.patch \
            file://1007-marvell-octeontx-tx2-Enable-bootretry-env-var-capabi.patch \
            file://1008-marvell-Enable-bootretry-env-var-capability.patch \
            file://1009-octeontx-pcie-console-Fix-shutdown-code.patch \
            file://1010-octeontx-pcie-console-Fix-nexus-header-version-numbe.patch \
            file://1011-drivers-spi-octeontx-use-read-after-write-for-MPI_CF.patch \
            file://1012-octeontx-pcie-console-rework-commit-5c90bf5-fix-nexu.patch \
            file://1013-octeontx2-96xx-fix-compiler-warnings.patch \
            file://1014-board-octeontx-Add-check-on-board-environment-variab.patch \
            file://1015-cmd-bootimgup-fix-crash-on-memory-corruption.patch \
            file://1016-cmd-bootimgup-fix-memory-leak-in-spi_flash_update.patch \
            file://1017-arch-octeontx2-include-pci-bootcmd-buffer-in-memory-.patch \
            file://1018-drivers-serial-pcie-console-remove-redundant-dm_fdt_.patch \
            file://1019-board-octeontx2-probe-serial-bootcmd-using-driver-in.patch \
            file://1020-fdt-Addition-of-mac-number-in-board-specific-node.patch \
            file://1021-arm-mvebu-Add-armada-DB-88F6820-AP-support.patch \
            file://1022-drivers-mtd-spi-nor-add-flash-entry-for-MT25QL02G.patch \
            file://1023-arm-mvebu-add-alternative-boot-device-code-used-for-.patch \
            file://1024-defconfig-db-88f6820-ap-enable-usb-to-ethernet-adapt.patch \
            file://1025-mvebu-spl-add-boot-from-nand-option.patch \
            file://1026-arm-mvebu-armada-388-gp-fix-spi-description.patch \
            file://1027-spi-kirkwood-prevent-limiting-speed-to-0.patch \
            file://1028-otx2-Added-initial-f95mm-support.patch \
            file://1029-arch-arm-dts-add-support-for-PCIe-EP.patch \
            file://1030-drivers-pci_endpoint-add-Marvell-PCIe-EP-driver.patch \
            file://1031-pcie-ep-Add-snic-EP-SRIOV-VF-ID-configuration.patch \
            file://1032-octeontx-mtd-Fix-crash-in-NAND-driver.patch \
            file://1033-83xx-add-pci-bootcmd-support.patch \
            file://1034-configs-add-defconfig-for-CN9130-CRB-board.patch \
            file://1035-include-configs-use-2MB-boot-on-9130-CRB-mmc-device.patch \
            file://1036-Fix-crash-in-PCI-console.patch \
            file://1037-Add-PCIe-console-support.patch \
            file://1038-Fix-PCIe-console.patch \
            file://1039-drivers-pci_endpoint-fix-mvebu_ep_uio-bar-setups.patch \
            file://1040-configs-mvebu-add-defconfig-for-cn9130-CRB-board-in-.patch \
            file://1041-arch-arm-dts-add-support-for-cn9130-crb-C-board.patch \
            file://1042-Revert-Fix-PCIe-console.patch \
            file://1043-octeontx-pci-console-Fix-PCI-console-shutdown.patch \
            file://1044-Revert-Revert-Fix-PCIe-console.patch \
            file://1045-armv8-add-return-code-definitions-for-smccc.patch \
            file://1046-thermal-a80x0-a70x0-change-thermal-sensor-API.patch \
            file://1047-thermal-a80x0-a70x0-use-smc-calls-for-thermal-sensor.patch \
            file://1048-arch-arm-add-support-for-cn9130-db-C-PCIe-EP.patch \
            file://1049-Bump-u-boot-2019.10-devel-to-release-1.0.0.patch \
            file://1050-drivers-pci_endpoint-fix-PCIe-bars-cleanup-in-mvebu_.patch \
            file://1051-ddr_phy-cn9130-Add-new-u-boot-command-for-ddr_phy-ac.patch \
            file://1052-drivers-pci_endpoint-use-resizable-BAR-caps-for-bar-.patch \
            file://1053-arch-arm-dts-increase-BAR2-size-to-16MB-for-PCIe-EP-.patch \
            file://1054-Allow-tuning-to-work-on-CN96xx-pass-C0.patch \
            file://1055-Bump-u-boot-2019.10-devel-to-release-2.0.0.patch \
            file://1056-arm-dts-cn9130-fix-model-name-of-DB-setup-B.patch \
            file://1057-arch-arm-dts-update-BARs-for-CP110-PCI0-EP-platforms.patch \
            file://1058-octeontx-octeontx2-Adjust-ram-size.patch \
            file://1059-arm64-mvebu-dts-cn913x-db-add-MMC-power-regulator.patch \
            file://1060-drivers-pci_endpoint-fix-bar-type-in-mvebu_ep_uio-dr.patch \
            file://1061-drivers-pci_endpoint-pcie_mvebu_ep_uio-increase-BAR-.patch \
            file://1062-arch-arm-mvebu-pci-bootcmd-support-on-PCIe-EP-platfr.patch \
            file://1063-net-mvpp2-add-explicit-sgmii-2500-support.patch \
            file://1064-net-phy-marvell-extend-88E2110-to-use-both-2.5GHz-mo.patch \
            file://1065-octeontx-octeontx2-Print-preserved-memory-if-request.patch \
            file://1066-arm64-dts-a8k-disable-UHS-modes.patch \
            file://1067-arm64-mvebu-config-enable-SD-MMC-highest-speed-modes.patch \
            file://1068-mmc-xenon_sdhci-improve-voltage-switch-sequence.patch \
            file://1069-arm64-dts-a8k-add-explicit-sgmii-2500-support.patch \
            file://1070-Bump-u-boot-2019.10-devel-to-release-3.0.0.patch \
            file://1071-net-mvpp2-resolve-MDIO-build-dependencies.patch \
            file://1072-net-mvpp2-use-new-MVMDIO-driver.patch \
            file://1073-arm64-dts-armada-8040-mcbin-fix-10G-PHY-reset-polari.patch \
            file://1074-net-mvpp2-sort-headers.patch \
            file://1075-net-mvpp2-remove-redundant-SMI-address-configuration.patch \
            file://1076-drivers-spi-octeontx-fix-memory-corruption-in-exec_o.patch \
            file://1077-drivers-spi-octeontx-Fix-memory-leak.patch \
            file://1078-drivers-mtd-spi-nor-update-4B_OPCODES-flag-for-n25q0.patch \
            file://1079-cmd-eth_cmds-add-set_an_lbk-command.patch \
            file://1080-spi-use-4B-opcode-for-mx66l1g45g.patch \
            file://1081-octeontx2-mmc-Allow-taps-to-be-overridden.patch \
            file://1082-octeontx2-mmc-Add-tuning-support-for-HS400-mode.patch \
            file://1083-configs-mvebu-add-support-for-MTD-and-UBIFS.patch \
            file://1084-include-configs-mvebu-fix-NAND-environment-location.patch \
            file://1085-driver-mmc-Fix-compilation-issues.patch \
            file://1086-octeontx2-mmc-Perform-DMA-cleanup-in-read-case.patch \
            file://1087-configs-mvebu-enable-mtd-command.patch \
            file://1088-cmd-marvell-eth_cmds-add-set-get_ignore-commands.patch \
            file://1089-octeontx-Add-support-to-set-individual-lmac-mac-addr.patch \
            file://1090-configs-81xx-update-text-base-to-0x2800000.patch \
            file://1091-scripts-ci-switch-the-baseline-to-2019.10.patch \
            file://1092-configs-mvebu-enable-MTD-support-in-all-A7K-A8K-conf.patch \
            file://1093-drivers-mtd-nand-raw-pxa3xx-disable-RAW-read-support.patch \
            file://1094-drivers-thermal-mvebu-fix-the-tsen-compilation-warni.patch \
            file://1095-octeontx-octeontx2-Print-preserved-memory-size.patch \
            file://1096-arm64-dts-cn9130-crb-fix-eth2-description.patch \
            file://1097-net-mvpp2-Fix-2.5G-GMII_SPEED-configurations.patch \
            file://1098-net-phy-marvell-remove-hardcoded-PHY-2210-lane-swap.patch \
            file://1099-net-phy-marvell-Fix-PHY-221-2.5G-speed-detection.patch \
            file://1100-net-phy-marvell-Fix-2210-link-and-speed-detection-re.patch \
            file://1101-arm-dts-remove-A3900-device-tree-files.patch \
            file://1102-efuse-Workaround-for-ERRATA-5073-on-CN91xx.patch \
            file://1103-Marvell-otx-otx2-Fix-bdk-config-name-to-retrieve-pre.patch \
            file://1104-octeontx2-mmc-Specify-output-tap-timing-in-ps.patch \
            file://1105-mmc-octeontx2-Fix-hold-timing-for-HS200-and-HS400.patch \
            file://1106-drivers-net-octeontx2-support-to-update-sh_fwdata-ma.patch \
            file://1107-drivers-pci-octeontx2-Limit-HW-issue-workaround-to-o.patch \
            file://1108-Bump-u-boot-2019.10-devel-to-release-4.0.0.patch \
            file://1109-octeontx-octeontx2-Remove-parse-and-display-of-prese.patch \
            file://1110-arm64-dts-marvell-introduce-armada-7040-db-F-topolog.patch \
            file://1111-mmc-octeontx-minor-cleanup-and-debug-support.patch \
            file://1112-arm64-mvebu-dts-cn913x-added-dts-for-cn9130-crb-r1p3.patch \
            file://1113-mmc-octeontx-Set-dat_null-when-clearing-failed-block.patch \
            file://1114-spi-Enable-4B-opcode-flag-for-several-flash.patch \
            file://1115-drivers-pci_endpoint-pcie_dw_mvebu_ep-fix-the-amount.patch \
            file://1116-drivers-pci_endpoint-pcie_dw_mvebu_ep-add-outbound-V.patch \
            file://1117-tools-mrvl_uart-remove-fast-download-option.patch \
            file://1118-configs-loki-add-RTC-support.patch \
            file://1119-config-loki-Enable-e1000-driver.patch \
            file://1120-thermal-mvebu-restore-thermal-error-checking.patch \
            file://1121-arm64-mvebu-soc-use-smc-calls-for-soc-type-and-revis.patch \
            file://1122-sar-mvebu-use-smc-calls-for-dfx-register-set-access.patch \
            file://1123-sar-mvebu-ap806-use-smc-calls-for-dfx-register-set-a.patch \
            file://1124-arm64-mvebu-soc-extend-dfx-smc-handler.patch \
            file://1125-cmd-marvell-Add-serdes-diagnostics-command.patch \
            file://1126-Bump-u-boot-2019.10-devel-to-release-5.0.0.patch \
            file://1127-board-octeontx2-update-CGX-count-for-LOKI.patch \
            file://1128-dts-cn913X-ep-add-cn9131-and-cn9132-C-topology.patch \
            file://1129-octeontx2_96xx_defconfig-add-Winbond-SPI-flash.patch \
            file://1130-octeontx-bgx-Pre-init-BGX-registers-for-1000BASE-X-o.patch \
            file://1131-mmc-octeontx-octeontx2-Fix-DMA-cleanup-operation.patch \
            file://1132-mmc-octeontx-Introduce-delay-for-DMA-operations.patch \
            file://1133-net-mvpp2-AN-Bypass-in-1000-and-2500-basex-mode.patch \
            file://1134-fix-marvell-rtc-errata-rtc-base-init.patch \
            file://1135-gpio-mvebu-gpio-enable-label-parameter-for-bank-s-na.patch \
            file://1136-This-adds-the-PCA9546-4-channel-i2c-bus-switch.patch \
            file://1137-net-mvpp2-remove-unused-define-MVPP22_SMI_PHY_ADDR_R.patch \
            file://1138-net-mvpp2-fix-missing-switch-case-break.patch \
            file://1139-drivers-mv88e6xxx-add-switch-id-6193x.patch \
            file://1140-Revert-drivers-mv88e6xxx-add-switch-id-6193x.patch \
            file://1141-cmd-marvell-add-mv88e6xxx-switch-util.patch \
            file://1142-Bump-u-boot-2019.10-devel-to-release-6.0.0.patch \
            file://1143-cmd-marvell-Update-PRBS-APIs-to-start-stop-per-QLM-l.patch \
            file://1144-cmd-marvell-eth_cmds-Update-set-get-ignore-to-accept.patch \
            file://1145-drivers-mtd-spi-add-BP3-support-for-micron-mt25ql02g.patch \
            file://1146-driver-mmc-Enable-mmc-driver-for-t98-and-f95mm.patch \
            file://1147-drivers-pci_endpoint-remove-DW-MVEBU-drivers.patch \
            file://1148-drivers-mtd-spi-nor-ids-Rename-mx25l12805d-to-mx25l1.patch \
            file://1149-drivers-net-otx2-support-up-to-five-5-CGX-blocks-i.e.patch \
            file://1150-Bump-u-boot-2019.10-devel-to-release-7.0.0.patch \
            file://1151-configs-mvebu-remove-mvebu_db_ep_cn91xx_defconfig.patch \
            file://1152-drivers-net-octeontx2-Remove-assumption-of-1-1-NIX-N.patch \
            file://1153-drivers-net-octeontx2-support-multiple-NIX-blocks.patch \
            file://1154-drivers-mtd-spi-nor-ids-Rename-mx25l6405d-to-mx25l64.patch \
            file://1155-configs-mvebu-update-HS200-to-HS400-support.patch \
            file://1156-drivers-mmc-xenon-enable-HS400-support.patch \
            file://1157-arch-arm-dts-enable-HS400-on-cn913x-db-board-eMMC.patch \
            file://1158-Bump-u-boot-2019.10-devel-to-release-8.0.0.patch \
            file://1159-tools-fix-the-boot-pattern-in-mrvl_uart.sh-script.patch \
            file://1160-drivers-spi-octeontx-Apply-correct-checks-on-conditi.patch \
            file://1161-octeontx3-Add-support-for-OcteonTX3-SoC-platforms.patch \
            file://1162-board-octeontx3-check-for-chip-type-in-fuse-register.patch \
            file://1163-drivers-mmc-Enable-for-OcteonTX3-platforms.patch \
            file://1164-drivers-pci-Enable-for-OcteonTX3-platforms.patch \
            file://1165-drivers-watchdog-Enable-for-OcteonTX3-platforms.patch \
            file://1166-drivers-net-octeontx-otx3-add-initial-support-for-t1.patch \
            file://1167-octeontx2_95xx_defconfig-Add-Winbond-SPI-flash-suppo.patch \
            file://1168-Revert-drivers-net-octeontx-otx3-add-initial-support.patch \
            file://1169-Revert-drivers-watchdog-Enable-for-OcteonTX3-platfor.patch \
            file://1170-Revert-drivers-pci-Enable-for-OcteonTX3-platforms.patch \
            file://1171-Revert-drivers-mmc-Enable-for-OcteonTX3-platforms.patch \
            file://1172-Revert-board-octeontx3-check-for-chip-type-in-fuse-r.patch \
            file://1173-Revert-octeontx3-Add-support-for-OcteonTX3-SoC-platf.patch \
            file://1174-Revert-configs-mvebu-remove-mvebu_db_ep_cn91xx_defco.patch \
            file://1175-u-boot-dts-disable-PCIE-on-CP0.patch \
            file://1176-u-boot-defconfig-cn9131-db-ep-C-added-PCIE-CONFIG.patch \
            file://1177-Bump-u-boot-2019.10-devel-to-release-9.0.0.patch \
            file://1178-configs-98xx-Increase-heap-size.patch \
            file://1179-configs-98xx-Disable-network-driver.patch \
            file://1180-qlm-command-Fix-prbs-command-syntax.patch \
            file://1181-Revert-configs-98xx-Disable-network-driver.patch \
            file://1182-net-mvpp2-add-rx-training-on-10G-port.patch \
            file://1183-configs-98xx-Enable-ethernet-interface-commands.patch \
            file://1184-u-boot-dts-cn9130-disabled-PCIE-on-CP0.patch \
            file://1185-Bump-u-boot-2019.10-devel-to-release-10.0.0.patch \
            file://1186-drivers-net-octeontx2-Set-correct-NPC-INTF-for-NIX1.patch \
            file://1187-net-mvpp2-fix-comphy4-phy-selector-bits-offset.patch \
            file://1188-otx2-cgx-Fix-cgx-mask-to-retrieve-cgx_id.patch \
            file://1189-common-update-add-support-for-SPI-flash-for-FIT-upda.patch \
            file://1190-configs-mvebu_-enable-FIT-update-and-DM-SPI-in-all-s.patch \
            file://1191-U-boot-will-use-SMC-calls-for-SERDES-diags.patch \
            file://1192-cmd-mvebu-map-fixed-window-size-bug.patch \
            file://1193-Bump-u-boot-2019.10-devel-to-release-11.0.0.patch \
            file://1194-cmd-marvell-Fix-SMC-call-for-serdes-settings.patch \
            file://1195-t96-Fix-Klockwork-with-NULL-derefence-issue.patch \
            file://1196-drivers-i2c-Add-support-for-higher-bus-speeds-above-.patch \
            file://1197-Revert-t96-Fix-Klockwork-with-NULL-derefence-issue.patch \
            file://1198-otx2-Fix-Klockwork-with-NULL-derefence-issue.patch \
            file://1199-mvebu-efuse-fix-ld-efuse-access-type.patch \
            file://1200-arch-arm-mach-mvebu-enable-TF-A-boot-and-secure-FW.patch \
            file://1201-board-Marvell-mvebu_armada-8k-enable-CONFIG_OF_BOARD.patch \
            file://1202-Bump-version-to-devel.patch \
            file://1203-drivers-mtd-spi-Add-MX66L2G45GXRI00-macronix-flash.patch \
            file://1204-drivers-fuse-mvebu-ld-Fix-CP-LD-fuse-program-sequenc.patch \
            file://1205-arch-arm-armada-3720-Fix-eMMC-card-detection.patch \
            file://1206-configs-98xx-Add-Winbond-SPI-flash-support.patch \
            file://1207-octeontx-nand-Clean-up-init-code.patch \
            file://1208-otx2-Added-smc-call-to-enable-WFE-per-core.patch \
            file://1209-cmd-eth_cmds-Update-set_ignore-description.patch \
            file://1210-CPU-related-info.patch \
            file://1211-smbios-type-4-implementation.patch \
            file://1212-smbios-type-7-implementation.patch \
            file://1213-smbios-type-8-implementation.patch \
            file://1214-smbios-type-9-implementation.patch \
            file://1215-smbios-type-16-implementation.patch \
            file://1216-smbios-type-17-implementation.patch \
            file://1217-smbios-type-19-implementation.patch \
            file://1218-smbios-type-20-implementation.patch \
            file://1219-smbios-type-41-implementation.patch \
            file://1220-smbios-count-no-of-records.patch \
            file://1221-smbios-version-changed-to-3.2.patch \
            file://1222-smbios-table-broken-in-absence-of-string.patch \
            file://1223-smbios-type_17-details-addition.patch \
            file://1224-board-marvell-Fix-disable_ooo-and-enable_wfe-smc-cal.patch \
            file://1225-board-marvell-Added-new-smc-call-to-disable-OOO-base.patch \
            file://1226-board-marvell-Renamed-enable_wfe-with-enable_wfe_mas.patch \
            file://1227-Revert-net-mvpp2-fix-comphy4-phy-selector-bits-offse.patch \
            file://1228-Revert-net-mvpp2-add-rx-training-on-10G-port.patch \
            file://1229-drivers-mtd-spi-nor-Add-protection-support-for-Macro.patch \
            file://1230-sandbox-correction-in-sandbox-cpu.patch \
            file://1231-configs-mvebu_armada-increase-the-NAND-u-boot-partit.patch \
            file://1232-serdes-Add-new-serdes-command.patch \
            file://1233-configs-mvebu-Add-support-for-ASIX-AX88179-USB2ETH.patch \
            file://1234-drivers-mtd-spi-Use-security-register-for-status-on-.patch \
            file://1235-net-tftp-Fix-too-small-block-size.patch \
            file://1236-otx2-Add-inject-optional-parameter-to-prbs-command.patch \
            file://1237-otx2-Fix-operations-order-for-mmc-set_ios-to-ensure-.patch \
            file://1238-modification-Change-in-copyright-message.patch \
            file://1239-Update-u-boot-2019.10-local-version-to-10.3.5.0-2.patch \
            file://0001-u-boot-dts-cn913x-com-express-type-7.patch \
            file://0002-u-boot-makefile-add-cn913x-com-express-type7-dts.patch \
            file://0003-config-cn913x-com-express-type-7-defonfig.patch \
            file://0004-u-boot-disable-board_fix_fdt-on-cn913x-com-epress-ty.patch \
            file://0005-u-boot-fix-i2c1-setting.patch \
            file://0006-build-dts-for-CN913x-CEx7-by-SolidRun.patch \
            file://0007-u-boot-config-Makefile-and-defconfig-cex7-cn913x.patch \
            file://0008-u-boot-update-device-tree-of-cn9130-cex7.patch \
            "

do_compile_prepend() {
    export DEVICE_TREE="${UBOOT_BUILDENV_DEVICE_TREE}"
}

SYSROOT_DIRS +=  " /boot "
